### PR TITLE
Adjusting games assets hierarchy

### PR DESCRIPTION
**Pull request by Booplicate**
I think it should be sorted. Especially if MAS will get more games.

In progress...
- [x] Move games assets (e. g.`.png`) into their personal folders in `mod_assets/games/`
- [x] Change assets location in `.rpy` files
- [x] ~~Figure out how to clean up game folder from unused files~~
- [x] Tests

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
we need to do update testing on this since it changes filepaths everywhere.

@Legendkiller21 I'm going to setup an update url with a build for this pull request later this week. Once that is done i'll have further instructions for you to test the update.

**Comment by ThePotatoGuy** [comment]
Okay make that later this week. I will try to make this testable while I am gone next week.

**Comment by ThePotatoGuy** [comment]
moving to 0.10.5 because of testing

**Comment by ThePotatoGuy** [comment]
@Legendkiller21 

So here's what you need to do to test:
1. download the mod from this url (https://monika-after-story.s3-us-west-2.amazonaws.com/dl/Monika_After_Story-0.10.3-Mod.zip)
2. install the mod via that build (it has a modified regular update url and version)
3. launch the game and make sure unstable updates is off. it should prompt u to update
4. update the game via in-game updater. 
5. verify everything still works after successfully updating.

**Comment by Booplicate** [comment]
> You've changed the permissions of the stockfish programs to `644`, can you change them back to `755`

That wasn't intentional, I tried to replace it with the ones from master, but it tells me that there is no difference between them. How can I fix it then? :thinking:

**Comment by ThePotatoGuy** [comment]
i did the permission change myself (also updated the win files to executables)

**Comment by ThePotatoGuy** [comment]
@Legendkiller21 still waiting on you to do an update test.

**Pull request merged**
