### PR TITLE
Added a "Plush Monika" topic

### PR DESCRIPTION
**Pull request by QuadILOP1**
Just a simple persistent value due to having or not having a Monika Plushie

### CODE REVIEW

**Comment by QuadILOP1** [comment]
Is anyone gonna check this stuff? It's been five days XD

**Comment by multimokia** [comment]
While it makes sense to bring this topic up, I don't believe this is the direction we wish to take it.

Referring to the plush as a child is a little excessive and will make people uncomfortable for sure. Plus it's a bit of a stretch. Additionally I feel like there can be more commentary especially coming from the current `monika_twitter`, where she mentions being reduced to a marketable asset -- this form of merch especially seems fitting for that. So I feel like a good direction would be to piggy-back this off of that topic by requiring that one to have been seen first, as well as adding some dialogue alluding to it.

**Comment by multimokia** [comment]
Additionally, player model variables should use the prefix `_mas_pm`, your variables only have the `_mas_` part.

They're also not the same variable used in the dialogue, I suggest using `_mas_pm_has_plush_monika` for verbosity.

**Comment by multimokia** [comment]
As of the discussion above, I will be tagging this under rewrite as the direction needs to be changed.

**Comment by QuadILOP1** [comment]
You got it. Just was throwing this in because I really didn't know where I was fully going with it tbh.

**Comment by multimokia** [comment]
Closing as no longer in development (confirmed via DM thru @Mugnika)

**Pull request closed without merging**
