### PR TITLE
Just a topic about the mod

### PR DESCRIPTION
**Pull request by KritRom**
Just a topic about how the mod works differently from DDLC. Hopefully Monika sounds like herself here.

### CODE REVIEW

**Comment by KritRom** [comment]
Uhh does anyone check on this stuff lol

**Comment by jmwall24** [comment]
@KritRom yes we do, we're busy with other stuff at the moment

**Comment by KritRom** [comment]
> @KritRom yes we do, we're busy with other stuff at the moment

Ah okay, I understand. Sorry if my precious comment seemed insulting.

**Review by jmwall24 — COMMENTED** [review]
Hmm not a bad topic, just not sure how much of it really works. Depending on when the player started, a fair bit of this isn't true. For older players she didn't delete the chr file right away and it WAS just empty space outside.

**Comment by KritRom** [comment]
Sorry for late reply, and I understand. The previous versions didn't have a lot of the features and it wouldn't make sense for some of the players. I'll edit the topic and fix this.

**Comment by KritRom** [comment]
The errors with the updated content branches are fixed, and I'll make an updated version of the topic itself later. For now, I'll leave it like this.

**Comment by jmwall24** [comment]
Closing as this doesn't really add anything not already covered.

**Pull request closed without merging**
