### PR TITLE
New BRB: I'm going to the toilet.

### PR DESCRIPTION
**Pull request by Wingdinggaster656**
See #7296.
I was actually a little bit surprised that we forgot this BRB.

### CODE REVIEW

**Comment by Booplicate** [comment]
I don't think we need a separate brb for this, it'd be rather weird to tell her this. Alternatively you could rework this into a "going to bathroom" brb.

**Comment by Wingdinggaster656** [comment]
> I don't think we need a separate brb for this, it'd be rather weird to tell her this. Alternatively you could rework this into a "going to bathroom" brb.

Is this strange? Actually even in real life, when dating each other, couples will tell each other "I want to go to toilet, wait a second" things.
Just suggestion, if you want me change, of course I will.

**Comment by multimokia** [comment]
Honestly this is kinda unnecessary, I think we can just keep this with the generics and not have a full brb for it

**Comment by Wingdinggaster656** [comment]
"Unnecessary"... True. But there is no harm to add this.
How about making a poll on Discord server? I'm not there so I don't know if this is possible, but I think this is a good idea.

**Comment by multimokia** [comment]
By unnecessary I mean unnecessary to have so much dialogue. The generic `I'll be right back` suffices and we can just add this there.

I don't think she needs to comment on you going to the washroom.

**Comment by Wingdinggaster656** [comment]
> By unnecessary I mean unnecessary to have so much dialogue. The generic `I'll be right back` suffices and we can just add this there.
> 
> I don't think she needs to comment on you going to the washroom.

Agree. Going to change this later.

**Comment by multimokia** [comment]
I meant using the system from #6853

This can be generic

**Comment by Booplicate** [comment]
Call it `bathroom`, please. It's more generic.

**Comment by Wingdinggaster656** [comment]
> I meant using the system from #6853
> 
> This can be generic

Used now.

**Comment by Wingdinggaster656** [comment]
> Call it `bathroom`, please. It's more generic.

Bathroom now.

**Comment by niapng** [comment]
I think that we need more brb tbh. 
For example "I'm going to walk my pet"

**Comment by Wingdinggaster656** [comment]
> I think that we need more brb tbh.
> For example "I'm going to walk my pet"

This is not really in need. Because not many people has a pet, I guess.
(Indeed, not many people do code work, too, but code is something related to Monika, so we have that "I'm going to code" BRB.)

**Comment by Booplicate** [comment]
After further discussion, we decided that this falls under generic "going to do something" and there's no need to be more specific about it.

**Pull request closed without merging**
