### PR TITLE
Added Options To Sleep Greeting

### PR DESCRIPTION
**Pull request by Rai99**
Also stole part of the greeting_goodmorning
#2024, #1524, #3383

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
Alright, I like that this will solve some of the sleep greeting issues we've been having. 2 things:

1. Currently we want to start making all time-based dialogue work with the custom sunrise / sunset settings. At the moment, there's no simple way to convert the sunrise/sunset time to a usable hour / mintue object, so we won't be merging this until that is in. I'll probably leave a comment here about it when its done.
2. Can you go through past issues and have your comment link them? You don't have to get every single one, but I'm almost 100% sure that at least one issue bfore mentioned the sleep greeting having no sense oftime.

**Comment by ThePotatoGuy** [comment]
Okay for point 1, just found a function I wrote a while back. `mas_cvToHM` converts minutes into `(hour, minute)`.

You can use this like this:
```python
sunrise_hour, sunrise_min = mas_cvToHM(persistent._mas_sunrise)
sunset_hour, sunset_min = mas_cvToHM(persistent._mas_sunset)
```

You might have to combine this with some of the `datetime` functions and `timedelta` to really get a correct time check for sunrise/sunset.

**Comment by ThePotatoGuy** [comment]
I might add some easier to use functions that just checks if the sun is up or not / midnight-sunrise / sunset to midnight/ and so forth.

**Comment by Rai99** [comment]
I'm not sure this needs to work with the custom sunrise/sunset times. I aimed to make it work and fit regardless of runrise/sunset, assuming the player went to sleep for the night and not just a nap (Which might need to be its own farewell and greeting)

I think 0-5 is universally seen as _really late_ or _the dead of night._ 

5-12 is a common time to wake up and is universally considered morning time.

12-15 was made with late risers in mind, who wake up after 12pm and probably before 3-4pm.

Every other time was made, keeping in mind that some people don't have time to visit Monika in the morning and have to visit her at the end of their day. 

I don't think this needs to tie into custom sunrise/sunset, but it might be able to fit in well to change 12-15 to 12-sunset_hour. Using sunrise_hour for the 0-5 threshold was also in mind, but some people have to start their day that early when it's still dark/the dead of night. 

Also, I wasn't sure if you planned to add anything else here about easier to use functions, so I held off on making any changes.

**Comment by ThePotatoGuy** [comment]
Well you may find the functions useful. They won't be in `content` until probably tomorrow or the day after so just hold tight.

**Comment by ThePotatoGuy** [comment]
suntime helper functions are in `content` now, please use those here.

**Comment by jmwall24** [comment]
this will be a part of #4914 current marked for 0.10.6

**Comment by multimokia** [comment]
Seeing all the changes which will result in the timeconcern overhaul, it's going to be incredibly difficult to take this format and retrofit it for the new functions and such.

We'll take what will work when the time comes to implement that.

Until then, this is closed.

**Pull request closed without merging**
