### PR TITLE
RecursionError greeting

### PR DESCRIPTION
**Pull request by scpketer**

### CODE REVIEW

**Review by ThePotatoGuy — COMMENTED** [review]
I wonder if we can make a joke in here where the dialogue repeats at least once before the recursion error occurs.

**Comment by scpketer** [comment]
\>I wonder if we can make a joke in here where the dialogue repeats at least once before the recursion error occurs.
I think we can, I'll work on it.

**Comment by multimokia** [comment]
Please allow maintainers to make edits to your PRs

**Comment by scpketer** [comment]
That's absolutely fine, turned it back on. Why pushing edits unannounced, though?

**Comment by multimokia** [comment]
Sometimes we're going to review and we've already pulled your pr. Easier to make the edits directly

**Comment by multimokia** [comment]
Just an FYI to not use `_` to represent garbage vars in renpy, `_` is reserved to mark strings as eligible for translation, which we do in menus and other areas. As such, if that gets changed to no longer be a function that accepts a string, all menus will crash.

Additionally, `renpy.call` when inside a `python` block will escape the python block, as renpy doesn't know how to get back to where it should go. For the dialogue loop to happen, you need to `while` loop it under a normal `call`.

**Comment by scpketer** [comment]
Thanks for fixing my poor code.

**Review by jmwall24 — APPROVED** [review]

**Review by multimokia — APPROVED** [review]

**Pull request merged**
