### PR TITLE
Adding Idle expressions

### PR DESCRIPTION
**Pull request by ThePotatoGuy**
#2055 

This also acts as an easy way to tell what affection level you are at.

## features
* idle mode now has varying expressions, based on affection
* talk and play menu dialogue is now different based on affection
* also added a neato dev line to disable the im sorry check

Idle expressions table:

| affection | sprite codes | descriptions |
|---|---|---|
| broken | 6ckc | broken or deranged? |
| distressed | 6rkc/6lkc | listly looking left and right, avoiding eye contact with player |
| upset | 2efc | looks angry |
| upset -> 0 | 1esc / 5tsc | non-smiling, bored |
| normal | 1esa | defualt |
| happy | 1eua | higher eyebrows than default |
| affectionate | 1eua / 1hua / 1sua / 1kua | variety of happy expressions |
| enamored | 1eua / 5esu / 5tsu / 1huu / 1sua / 1kua | variety of happy expressions |
| love | 1eua / 5esu / 5tsu / 1huu / 5eubla / 1sua / 1kua | variety of happy expressions |

The affectionate+ expressions use a particular set of percentages explained on the doc.

The talk and play menus use `MASQuipLists`, but are only limited to lines.
These are created in `mas_affection`.

## Testing
1. set random chatter to never
2. for each affection level, observe monika in idle mode.
3. also check talk menu and play menu for the changed dialogue.

Before testing upset and below, you should set `persistent._mas_disable_sorry` to True to stop the imsorry check from being brought up and enforced.

**NOTE** this is on content because of the art. Dialogue is so small so no review needed.

### CODE REVIEW

**Comment by multimokia** [comment]
Regarding the dialogue for the menu which will replace the "what would you like to talk about" bit, for the `love` affection level, maybe you could implement a short list, similar to the one for handling giving Monika a nickname, and the `love` dialogue could be changed to `"Yes, [p_nickname]"` (variable name is obviously just for demonstration) and have a random number generator pick from the list, so you have more affectionate responses for the level. For example: "Yes, dear?", "Yes, sweetheart?", ""Yes, honey?", etc. Just my thoughts!

**Comment by jmwall24** [comment]
Agreed.  I really hope 'What's up?' is a placeholder lol

**Comment by ThePotatoGuy** [comment]
`love` is supposed to be like the comfortable stage in a relationship, so the `Yes, [x]?` ones would more likely fit in the enamored state actually.

**Comment by ThePotatoGuy** [comment]
@aldoram5 dont merge, going to change the quips into a framework version so we can make then randomized

**Comment by ThePotatoGuy** [comment]
@multimokia @jmwall24 

Can you list out a variety of what the talk / play menus should show based on affection? just comment them on this pull request, please.

like:
### broken
* "..."
* "something"
* "something else"

**Comment by jmwall24** [comment]
Ok, here's what we're thinking for low affection:

**For Talk:**

**broken** (I actually kind of like **just** having "..." for this and using the others for distressed)
- "..."
- "...Oh?"
- "...Huh?"
- "...Yes?"
- "...Hm?"

**distressed**
- "We can try talking, I guess."
- "I guess we can talk."
- "Oh...you want to talk?"
- "If you want to talk, go ahead."
- "We can talk if you really want to."
- "Are you sure you want to talk to me?"
- "You actually want to talk to me?"

**upset**
- "What?"
- "What do you want?"
- "What now?"
- "What is it?"
- "Fine...we can talk."
-  "If we have to talk, go ahead."
- "Just...whatever, go ahead."


**For Play:**

**broken** (same as talk, probably just "..." but can use the others here, if not can be used for distressed
- "..."
- "...Fine."
- "...Sure."

**distressed**
- "I guess we can play a game."
- "I guess, if you really want to."
- "I suppose a game would be fine."

**upset**
- "...Which game?"
- "Okay...whatever, choose a game."
- "Fine, pick a game."

**Comment by multimokia** [comment]
Right then!

###So for the normal talking menu:###

###Normal/Happy###
- "What would you like to talk about?"

###Affectionate/Enamored###
- "What would you like to talk about? <3
- "What would you like to talk about, honey?"
- "Yes, sweetheart?"
- "Yes, honey?"
- "Yes, dear?"
- "What's up, honey?"
- "What's on your mind, darling?"
- "What would you like to talk about, sweetie?"

###Love###
- "Hey, what's up?"
- "What's on your mind?"
- "Anything on your mind?"
- "What's up, [player]?"
- "What's up?"
- "Anything you'd like to talk about?"
- "We can talk about anything you like, [player]."


###For Games:###

###Normal###
- "What would you like to play?"
- "What did you have in mind?"
- "Anything specific you'd like to play?"

###Affectionate/Enamored###
- "Choose anything you like, honey."
- "Pick anything you like, sweetheart."

###Love###
- "Yay! Let's play together!"
- "I'd love to play something with you!"
- "I'd love to play with you!"

**Comment by ThePotatoGuy** [comment]
@multimokia do you have happy options for games or should i use normal there too

**Comment by multimokia** [comment]
Ah, should have cleared that up, I was going for em as both

**Comment by ThePotatoGuy** [comment]
also I'm going to move the pet names to enamored and use playername in place for petnames in affectionate

**Comment by multimokia** [comment]
Sounds good to me!

**Comment by ThePotatoGuy** [comment]
@aldoram5 this is ready for another pass and merge

**Comment by aldoram5** [comment]
Hi @Bam8647!
Please post these kind of questions as issues, that way if someone else has a similar issue or knows the answer can answer you more quickly, because these are more to discuss about features before they're added.
As for your questions it has been added to today's release 0.8.6, and if you don't notice much difference, chances are that Monika isn't too affectionate with you yet.

**Comment by AsuraShun** [comment]
it looks like the ''asking how she is'' out of question,if so,it's a shame

**Pull request merged**
