### PR TITLE
Adding a new normal story

### PR DESCRIPTION
**Pull request by Yazijustmonika**
This is a classic moral story from my country Indonesia and I want to share it to everyone through Monika.
I might have grammar mistakes or expression mistake in there cause my english is not that good, so im grateful if there's someone who would fix it.
and I hope that this story could get accepted.
Have a nice day everyone.

### CODE REVIEW

**Comment by disownxd** [comment]
I don't want to sound petty or anything, but I don't agree with "Your mother is the one who raised you since you are born, and nothing could exchange her love for you."

Many people aren't raised by their mothers, and I am one of them. In fact, my own mother didn't want anything to do with me. I was raised by my grandma, and many other people are raised by fathers, uncles, aunts, brothers, sisters, guardians...

Not every mother is good.

I guess a better way to say it's "Respect the person who raised you, because they gave everything in their power to make you happy", or something like that.

I really have my best intentions when I say this, and I hope I didn't sound rude or anything. Besides, it's a really great story.

**Comment by WishStone-Dragon** [comment]
> I really have my best intentions when I say this, and I hope I didn't sound rude or anything. Besides, it's a really great story.

I don't think your input is rude at all. 
I would also add that blood is NOT thicker than water. Anyone who has been abused by their family had to face the point where 'but they are my family and I should stand by them' needed very critical review. Sometimes cutting ties even with those who raised you is very important.

**Comment by disownxd** [comment]
I absolutely agree with you. Also, sometimes people who aren't blood related to you help you and appreciate you more than your own family. Maybe a better aproach would be "Respect the people who supported you in moments of need"?

**Comment by Yazijustmonika** [comment]
> I really have my best intentions when I say this, and I hope I didn't sound rude or anything. Besides, it's a really great story.
@disownxd no no, its not rude at all, i was also that i might have mistakes there so feel free to fix it, and i basically agree with you @WishStone-Dragon blood is not thicker than water, i actually also not raised by my biological mother so i understand, its just i dont know what should i add in the moral, the point is i only want to add that story

**Comment by jmwall24** [comment]
Closing as the moral of the story is something that could potentially cause trauma to individuals who have had bad experiences with their parents/guardians.

**Pull request closed without merging**
