### PR TITLE
Add outfit options to sprite JSON

### LINKED ISSUE #7983: add matching hair/ACS info to clothes sprite JSON
currently the pattern for making an "outfit" (like outfit mode), is to include an entry prog point that checks outfit mode and manually changes the hair or ACS. I think a better forward-thinking solution is to include an entry in the sprite jsons for clothes where hair/ACS can be listed, and those entries can be auto-worn if outfit mode is checked and the system is able to find them. (also auto-removed if outfit mode is on)

Notes:
* should run this after entry progpoints but allow entry progpoints to stop auto-wearing of specific hair/ACS
* would need additional information on the sprite object to link matching sprite objects
* verification of existence would have to happen at the end of sprite object parsing, and also should be warn-logged (not error)
* not planning to add conditional hair/ACS. prog points should be used if something requires more logic than just checking if outfit mode is enabled

### PR DESCRIPTION
**Pull request by ThePotatoGuy**
waiting on #7988 
closes #7983

# TODO
- [x] change current JSONs to use instead of prog points and test
- [x] make `outfit_hair` accept strings
- [x] add logging
- [x] move spritepack-based ones to separate pr

# Key Changes
* adds outfit options to `MASClothes` and jsons to auto add and remove items in outfit mode without manual prog point code. (see outfit mechanics below for details)
* `MASMonika.set_acs` - wears/removes an ACS based on a passed in truth value - use this to avoid branching manually between `wear_acs` and `remove_acs`
* `mas_utils.nested_defaultdict` - builds n-level `defaultdicts` (max level of 10 to avoid abuse)
* minor refactoring of top level sprite json processing
* **Clothes have been moved to after ACS in zz_spriteobjects**. This is to make sprite object creation possible with object refs instead of only string names.
* prog points have been modified or removed for the following clothes:
    * default (blazer) 
        * entry - outfit data removed
    * blackpink dress
        * entry - removed
        * exit  - removed
    * rin
        * entry - removed
    * marisa
        * entry - removed
        * exit - outfit data removed
    * miku
        * entry - outfit entry data used to determine if acs will be worn
    * sakuya
        * entry - outfit entry data used to determine if acs will be worn
    * spider lingerie
        * entry - removed
        * exit - removed
    * santa
        * entry - removed
        * exit - removed
    * santa lingerie
        * entry - removed
        * exit - removed
    * new years
        * entry - removed setting Hair and ACS in outfit mode
    * sundress white
        * entry - removed
        * exit - removed outfit mode specific lines
* the following spritepacks have been modified
    * orcaramelo - hatsune miku
        * added outfit hair and outfit ACS
    * orcaramelo - sakuya
        * added outfit hair and outfit ACS

### outfit mechanics

`MASClothes` objects now have 2 new properties:
* `outfit_hair` - the `MASHair` object to wear in outfit mode
     * a string is also accepted - this is processed layer (see below)
* `outfit_acs` - list of `MASAccessory` objects to wear in outfit mode
     * a list of strings/ACS objects are also accepted - this is processed later (see below)

Hair/ACS outfit processing is delayed on startup until sprite jsons are processed since not all hair or ACS will be loaded during `zz_spriteobjects`. The processing is contained entirely with `MASClothes`.

`MASMonika.change_clothes` now creates 2 `MASOutfitChangeData` objects and passes them into the various prog points. 
For the clothes entry and exit prog points , see the `outfit_exit_data` and `outfit_entry_data` params.
For prog points that have a `temp_space`, the data is stored in `temp_space` under the same names.

The `MASOutfitChangeData` objects contain the hair and ACS objects that may be added or removed in outfit mode. This class contains some functions for prog points to control whether or not those hair/ACS objects actually get added or removed. Note that hair is never auto-removed so attempting to enable/disable hair removal will not have an effect.
* `set_acs_change` - enables or disables wearing/removing for a specific ACS
* `set_acs_change_all` - enables or disables wearing/removing for all ACS
* `will_acs_change` - returns whether or not a specific ACS will be worn/removed
* `set_hair_change` - enables or disables wearing hair
* `will_hair_change` - returns whether or not the hair will be worn

Actual outfit adjustments happens in the `clothes_exit_pst_change` and `clothes_entry_pst_change` prog points. This allows the clothing entry/exit prog points to enable/disable outfit mode changes as appropriate. 

### outfits in JSONs

2 new props for sprite jsons:
* `outfit_hair` - should contain the name of the hair sprite object
* `outfit_acs` - should contain a list of ACS sprite object names

# going forward
* clothes that have outfit hair/ACS should use the new props instead of prog points.
* prog points should still be used if something is **not** outfit-mode dependent. for example: always removing an ACS on exit.

# Testing
* verify that all the clothes and spritepacks mentioned above in changes work appropriately when outfit mode is enabled/disabled.
* Also test cases where not all sprite objects exist for a clothes - like if the hair / ACS set in the outfit props is missing from the mod.

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
marking dont merge because this should be merged before next main release as it has spritepack changes that cannot be tested in unstable

**Comment by ThePotatoGuy** [comment]
^actually should split the spritepack parts out for testing

**Review by multimokia — APPROVED** [review]

**Review by Legendkiller21 — APPROVED** [review]

**Comment by ThePotatoGuy** [comment]
ok, slating this for merge in about 2 weeks (6/4).

**Comment by ThePotatoGuy** [comment]
oh i forgot thati moved spritepack changes outside of this pr so it CAN merge lol

**Pull request merged**
