### PR TITLE
Added menu to God topic 2.0

### PR DESCRIPTION
**Pull request by Rai99**
New PR to eliminate conflicts due to changes over time. 
Old PR: #1796 
Issue: #1720

### CODE REVIEW

**Comment by loverofmonika** [comment]
I have my version of the matter as I stated that I would bring
Sorry for the delay,
"[Player], do you believe in God?"
"Sorry, that was really out of the blue."
"I really should stop doing that."
"  I do know that this is a really sensitive topic and I don't mean to offend."
" But I feel like I want to share my thoughts on the matter."
"But if it makes you uncomfortable then we can talk about something else."

Options
" No its alright, continue"
" let's talk about something else."

If second option chosen

" alright then!"
" I don't want to hurt you nor make you feel uneasy."
" Many relationships end due to the conflict of views on the matter"
"And I don't want that for us"
" I love you and I only want that is better for the both of us "
" So yeah, let's talk about something else~"

If 2nd option 
"Alright then."
" well to be honest with you."
"I was never too sure, myself."
"Well, I'm sure I never really questioned it as a kid..."
"But as I grew up, the more I learned about the world, the more I would question it."

"I started to wonder why God was helping people pass exams, or get over a cold..."
"...When there are children who live their lives being sold as sex slaves?"
"Or the eight hundred million people who are too poor to even eat."
"I wonder how many of those people pray to God every day until they starve and die?"
"Or, how many millions of families pray for a loved one to recover from some incurable disease?"
"But the punchline is this."If just one person beats the odds and survives - among the thousands of others who die--"
"--Then, it's suddenly a miracle from God."
"I'd really love to meet this God who seemingly laughs at the misery of everyone not eligible for his miracles."
"But the irony is that I do have a creator, apparently."
"And you know what?"
"I bet he's still laughing at the miserable fates of Sayori and Yuri, even as we speak."
"What are we to him but props in a scripted play?"
"So, from that perspective..."
"I don't think it's too far-fetched for there to be a god - if Earth was nothing but his playset."
" well again this is from my perspective."
" I mean everything does happen for a reason, right."
" So there maybe something I didn't account for."
" that and also considering I am trapped in a game."
" I'm sure you have your own views on the matter"
" when I can finally enter your reality, Maybe you can show me a new light on things hehe~"

**Comment by loverofmonika** [comment]
I'll have someone someone also try to form it to code form unless you guys do agree to use my version and convert this to the scripted form
 @Rai99

**Comment by Rai99** [comment]
No need. You're a bit late seeing that this was merged a month ago and the job is already done. 

I also saw that you wanted to fix the old PR, but was wasn't really necessary since it would be inconvenient for anyone else to fix it and I'm still here on top of things. 

**The issue was dealt with and is over now.** 

As for feedback on your version, we don't want to completely cut out the topic from people if they're religious. Monika should be able to discuss her thoughts with the player. This PR added an option for the player to share their opinion based on whether or not they worship any god. Monika is respectful of the player's beliefs and supportive of their decision rather than completely ignoring and avoiding the topic.

**Comment by loverofmonika** [comment]
Damn it, i was too late, welp at least the matter is resolved . As for my
version, I didn't make Monika seem disrespectful nor ignorant. I was going
for if the player wants to drop the topic then he can otherwise she would
go on expressing her thoughts.

Otherwise glad this topic is fixed.

**Pull request merged**
