### PR TITLE
[New Spritepack] Dress (Dark blue, sparkly)

### PR DESCRIPTION
**Pull request by kkrosie123**
This is one of many new, upcoming spritepacks for future updates.

TODO:
- [x] less blurry thumbnail
- [ ] perhaps add other variants (Debating if they should be in the same PR)

### CODE REVIEW

**Comment by kkrosie123** [comment]
Thumbnail done. _Dress (Dark blue, sparkly)_ is ready for review and technically complete.

**Review by ThePotatoGuy — CHANGES_REQUESTED** [review]
is the vcut crossed straps tank top supposed to be part of this?

**Comment by kkrosie123** [comment]
> is the vcut crossed straps tank top supposed to be part of this?

There was a name error - it was called `brair` instead of `briar`, just decided to fix it, so yeah

**Comment by ThePotatoGuy** [comment]
that's gonna mess up user installs if they install all spritepacks at once. But should be easy to diagnose and resolve so probably ok.

**Review by ThePotatoGuy — APPROVED** [review]

**Comment by kkrosie123** [comment]
Ah. My bad.

**Review by lunulae — APPROVED** [review]
Tested, if we're still good with keeping the vcut changes this is ready to go~

**Pull request merged**
