### PR TITLE
your appearance

### PR DESCRIPTION
**Pull request by moonsandstar-s**
I could write a bunch about it, but this is a topic where you're able to tell Monika how you look. Complete with all options to cover pretty much any person that ever existed. Hope you enjoy! 
Thanks to @Olliesama for all the help with editing and coding.

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
Please base your changes to `content`.

**Comment by moonsandstar-s** [comment]
Done, @ThePotatoGuy , sorry about that!

**Comment by aldoram5** [comment]
Hi moonsandstar-s!
You should do it like @juliathegolden did for https://github.com/Monika-After-Story/MonikaModDev/pull/1557 opening another one with the requested base branch from the beginning https://github.com/Monika-After-Story/MonikaModDev/pull/1559. Doing a git rebase is an option too but that's a bit more complicated.
Also I noticed that you aren't adding an event for this topic, if you don't add it there's no way for the topic to be triggered so you may want to fix that too.

**Comment by Olliesama** [comment]
Haha...that was actually my bad.  Can't believe I forgot that.

**Pull request closed without merging**
