### PR TITLE
2B spack

### PR DESCRIPTION
**Pull request by ThePotatoGuy**
#9376 

# Key Changes
* adds 2b spack - thumbs is already included
* adds 2b o31 intro
* adds "hide-ring" ex-prop
## TODO
* [x] add o31 intro dialogue

# Testing
* verify looks good
* verify ring is hidden when outfit is worn and is worn again when outfit is taken off (if applicable)
* verify o31 intro event works

### CODE REVIEW

**Review by jmwall24 — CHANGES_REQUESTED** [review]
We need to add an ex_prop to toggle the ring off for gloves so we don't have potential clipping

**Comment by hatanasinclaire** [comment]
> We need to add an ex_prop to toggle the ring off for gloves so we don't have potential clipping

The gloves actually obscure the ring entirely on poses 2, 3, and 5! The position of the ring finger makes it so players would have to have replaced the ring with something extremely wide for it to not be completely covered.

**Comment by jmwall24** [comment]
@hatanasinclaire the issue is some players have commissioned rings with stones which is what worries us a bit. Having an ex_prop available for gloves (not just the gloves here, but any gloves) is an easy, safe way of making sure no one ends up with clipping.

**Review by Booplicate — APPROVED** [review]
@hatanasinclaire great work on the outfit

**Review by jmwall24 — APPROVED** [review]

**Review by Legendkiller21 — APPROVED** [review]

**Pull request merged**
