### PR TITLE
New Mood - I’m feeling…>…excited.

### PR DESCRIPTION
**Pull request by kkrosie123**
New mood.

### CODE REVIEW

**Comment by hussien0802** [comment]
how do you download this?

**Comment by kkrosie123** [comment]
> how do you download this?

It should be merged into the mod eventually after some edits. :)

**Comment by zwartkop2** [comment]
I think there should be a path in September for if the player is excited Monika's birthday coming up.

**Review by jmwall24 — APPROVED** [review]

**Review by multimokia — APPROVED** [review]

**Comment by kkrosie123** [comment]
speedrun pr

**Pull request merged**
