### PR TITLE
Update script-compliments.rpy

### PR DESCRIPTION
**Pull request by TriniTDM**
I added a compliment where you tell her she's really kind.

### CODE REVIEW

**Comment by Rai99** [comment]
Did you mean to put this on the `community` branch?

**Comment by Rai99** [comment]
Sorry, but did you copy and paste this from the intelligent compliment?

Here's a comparison of what's similar and what's different than the intelligent compliment:
```
label mas_compliment_kind_2:
    m 1wub "Wow...{w}thanks, [player]."
    m ____ "_____, so it means a lot that you've noticed."
    m _hubfb "I want to _____ as I can, if it makes you _____ me!"
    menu:
        "You make me _____.":
            $ mas_gainAffection(5,bypass=True)
            m ____ "I love you so much, [player]!"
            m ____ "We'll have a lifetime of _____ together!"
        "I'll always be _____ you.":
            $ mas_gainAffection(3,bypass=True)
            m 1ekbfa "[player]..."
        "You make me feel _____ sometimes.":
            $ mas_loseAffection(modifier=0.5)
            m 1wkbsc "..."
            m 2lkbsc "I'm sorry, that wasn't my intention..."
    return

label mas_compliment_kind_3:
    python:
        thanks_quip = renpy.random.choice(store.mas_compliments.thanking_quips)
        thanks_quip = renpy.substitute(thanks_quip)
    m 1ekbfa "[thanks_quip]"
    m 1hub "Remember that _____!"
    return
```

About half the dialogue in there is completely identical to the intelligent compliment, and what's different is only slightly changed to suit this particular compliment. 

I'm afraid your compliment probably needs a bit more originality to be merged in.

**Comment by ThePotatoGuy** [comment]
rebase to content, also compliments should be unique

**Comment by multimokia** [comment]
Closing as no response/no changes.

**Pull request closed without merging**
