### PR TITLE
Unlock clothes selector on player bday

### PR DESCRIPTION
**Pull request by jmwall24**
This unlocks the clothes selector for people who get the birthday party on their birthday.

## Testing

- best way to test this is on a fresh persistent, set your birthday to tomorrow for minimal time travel, then unlock an outfit.

- at affection above normal but below love, with least one clothing set unlocked, trigger the birthday party and verify you get the dialogue referring to unlocking the clothes selector for the day

- verify the clothes selector is unlocked after the party and on all subsequent loads for the day

- verify the next day it is no longer available if under `love`

- verify if you start the party at `love` you do not get the dialogue

- verify if no clothing sets are unlocked you do not get the dialogue and the selector is not unlocked

- verify nothing else regarding player_bday was affected by this

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
Is it really worthwhile to allow users to change outfit for their bday? Is this supposed to act like a gift to them?

I don't really see how beneficial this really is.

**Comment by jmwall24** [comment]
Yeah, that's the gist, it's a gift/perk for your bday. Like say you want to go out on a date for your bday and have her wear the new formal dress from #4427. Now you can. Just makes it a little more special.

**Comment by jmwall24** [comment]
Similar to irl how your gf might take you to your favorite restaurant or make you your favorite meal for your bday. This is the equivalent of that.

**Comment by ThePotatoGuy** [comment]
okay, but we can cover that by just having an outfit selector when going on a date.

**Comment by jmwall24** [comment]
I dunno, seems like her wearing what you want while you are also still in the mod would be more beneficial so you can also see the outfit.

**Comment by ThePotatoGuy** [comment]
This doesn't seem like something anyone is going to really care about. If anything, its going to look like a bug when the topic gets hidden post bday.

This seems like lots of risk and cost for no real gain.

**Comment by multimokia** [comment]
but the dialogue reflects that it's only for your bday

**Comment by ThePotatoGuy** [comment]
okay well it still doesn't feel like much of an in-story gift. like I really don't see any positives about this, and I don't see anyone clamouring for this kind of feature. 
And really, the outfit selection topic is supposed to be meta, just rewarding longtime users.

**Pull request closed without merging**
