### PR TITLE
Love Topic Randomiser

### PR DESCRIPTION
**Pull request by Olliesama**
Changes Monika's response to the player saying I love you to a random line after saying she loves you too.

### CODE REVIEW

**Comment by kaido1224** [comment]
A few typos I noticed:
 "You're the best parner I could ever want!",
should be: 
 "You're the best partner I could ever want!",

"I'll never hurt you betray you.",
not sure if this is supposed to be:
"I'll never hurt or betray you."
or
"I'll never hurt you."
or
"I'll never betray you."

"You're saved me in so many ways, how could I have not feel for you?",
should be:
"You've saved me in so many ways, how could I have not feel for you?"

**Comment by Olliesama** [comment]
Thanks for pointing it out. :)

**Comment by Olliesama** [comment]
Updated to include a counter that changes how Monika initially responds.

**Comment by Ulvsblakk** [comment]
That's a very interesting set up. I'm fond of the idea

**Comment by ThePotatoGuy** [comment]
I've fixed your indentation issues, but I won't do this everytime. Please refer to the [Style guide](https://github.com/Backdash/MonikaModDev/blob/master/STYLE.md) when writing a lot of code.

**Comment by Olliesama** [comment]
That's odd, it ran fine for me...Thanks you though.

**Comment by ThePotatoGuy** [comment]
It's not about it running fine or not, cause it will run fine even with terrible indents. It's about being consistent with the rest of the code, which uses 4 space indents.

**Comment by kaido1224** [comment]
I'm testing out your stuff Finale. 

I'd highly recommend putting in some notes so that it makes it easier for others to figure out what exactly your code is doing. It'll make testing and verifying what exactly it's supposed to do easier for others as well as for yourself some day if you come back and want to make changes to it.

**Comment by Olliesama** [comment]
Thanks for pointing out the poor grammar, I'll fix it and comment it for other people.

**Comment by kaido1224** [comment]
Thanks for adding the comments. @ThePotatoGuy I think this is good to go. Just needs review from an editor now.

**Pull request merged**
