### PR TITLE
Connect 4 (again, but better this time)

### PR DESCRIPTION
**Pull request by AlmaHue**
It still has the same AI, and still minimal dialogue too, but now the board uses a Displayable class.

### CODE REVIEW

**Comment by Booplicate** [comment]
You could continue working in #6929.

**Comment by AlmaHue** [comment]
multimokia said PRs should go to the content branch (the old one was in master), so I made a new PR. Except if it's impossible to change branch for each PR commits then my bad!

**Comment by ThePotatoGuy** [comment]
I changed your base branch in that PR so it was fine.

**Comment by ThePotatoGuy** [comment]
If these changes are ready for review, then just merge these commits to your connect4 branch

**Comment by AlmaHue** [comment]
@ThePotatoGuy I didn't see that... Sorry!

**Comment by AlmaHue** [comment]
> If these changes are ready for review, then just merge these commits to your connect4 branch

I'll be sure to do that next time

**Comment by jmwall24** [comment]
Closing in favor of #6929 these look to be the same now.

**Pull request closed without merging**
