### PR TITLE
MAS persistent updates

### PR DESCRIPTION
**Pull request by kaido1224**
Updated some of the MAS specific persistents to meet the naming convention

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
Is `player_dialogue` used anywhere else other than in the old keyword system?

**Comment by ThePotatoGuy** [comment]
What I mean is that if it's only used in outdated code, we should just comment it out (along with that keyword section).

**Comment by kaido1224** [comment]
Oh Gotcha, I have no clue. I'll look when I get a chance.

**Comment by kaido1224** [comment]
disregard this

**Pull request closed without merging**
