### PR TITLE
Quipped Notifs

### PR DESCRIPTION
**Pull request by multimokia**
Changed the notif display label into a method for some simplification and cleanliness, also the method takes in a list instead of a string for the body param, so notifs can be quipped by just passing a list in.

### CODE REVIEW

**Comment by him157** [comment]
huh,just asking,after this got passed,do I- I mean,we need to change the script?
if so I'm ready.

**Comment by multimokia** [comment]
Yeah, when this gets merged, you'll need to merge enhancement into your branch, then adjust your topics to match this format then.

**Comment by him157** [comment]
alright seems like it is time for me to work

**Comment by him157** [comment]
uh,ehehe... how do I add the enhancement in the PR?

**Comment by ThePotatoGuy** [comment]
wait for it to be released

**Comment by him157** [comment]
well thank you,you know what,thank all of you that work so hard on this mod.

**Pull request merged**
