### PR TITLE
New Topic - Early examples of AI

### PR DESCRIPTION
**Pull request by Wingdinggaster656**
See #7199, I think this idea would be nice.
Any suggestion would be nice to me, too.

### CODE REVIEW

**Comment by Wingdinggaster656** [comment]
Alright, conflict solved now. I should base my branch on content branch from the beginning...

**Comment by jmwall24** [comment]
I love the subject of the topic and appreciate the effort here. As it seems English is not your main language, I am assigning this to myself and will rewrite it so it's more fitting with the mod. I hope you don't take offense to this, but it just needs more than simple editing and will be easier for me to just make the necessary changes. But again, thanks for taking the time to do this, we really appreciate it.

**Comment by Wingdinggaster656** [comment]
> I love the subject of the topic and appreciate the effort here. As it seems English is not your main language, I am assigning this to myself and will rewrite it so it's more fitting with the mod. I hope you don't take offense to this, but it just needs more than simple editing and will be easier for me to just make the necessary changes. But again, thanks for taking the time to do this, we really appreciate it.

As long as my idea is still around, I don't mind too much. I've seen the changes you've made and I think they're good.

By the way, just out of curiosity, did you find out about this after reading what I wrote and checking out Sophia Robotics?

**Comment by jmwall24** [comment]
Yeah, I had never actually heard about Sophia before. Had to do some research lol

**Review by jmwall24 — APPROVED** [review]

**Review by multimokia — APPROVED** [review]

**Pull request merged**
