### PR TITLE
Fix consistence issue with monika_ribbon

### PR DESCRIPTION
**Pull request by kaido1224**

### CODE REVIEW

**Comment by multimokia** [comment]
Going to ref the issue here as well so it's easier to track there #3803

**Comment by TheSuperStu** [comment]
Hey.
A couple of lines down in the same topic, line 3435, needs an indent.

**Comment by multimokia** [comment]
No it doesn't. That dialogue goes with both paths.

**Comment by TheSuperStu** [comment]
Ah whoops, I see it now, sorry about that!

**Pull request merged**
