### PR TITLE
Interrupting each other

### PR DESCRIPTION
**Pull request by Freshairkaboom**
Adds small chance for special dialogue with Monika if you talk just before she's about to say something.

Anything here is still subject to tweaking, but it's been tested and seems to run smoothly. At the moment I've chosen less than 2 seconds before she starts talking, so on lower random chatter settings it's going to be really hard to do on purpose. It's meant to be a very rare occurrence.

The way it is currently set up, it shouldn't ever trigger when Monika is not about to say something, such as when the random chatter setting is set to "Never". This way, you know that if you trigger this piece of dialogue, Monika was actually about to start talking when you pressed "Talk".

Huge thanks to @TarossVelin for his issue suggestion in #6239 , and the devs for doing a lot of the heavy lifting behind the scenes.

Co-Authored-By: TarossVelin <43471712+TarossVelin@users.noreply.github.com>

### CODE REVIEW

**Review by multimokia — CHANGES_REQUESTED** [review]
Code review and dialogue review

**Comment by jmwall24** [comment]
Pushing this back. It needs some work in regards to flowing to the random topic if you let her go ahead. Many topics start with her getting your attention, which she already has here.

**Comment by jmwall24** [comment]
Do to changes to this PR and those changes' similarity to something else I've been working on, I merged my branch into this so we can do it all in one go. Not sure it'll all get done this release or not, so changed the milestone.

**Comment by multimokia** [comment]
Going to open this up further for community involvement. Figure with more of us involved, we can make topics which are initiated from repeat convo lead in totally differently, adding more realism and acting more like you prompted the conversation and not Monika.

**Comment by multimokia** [comment]
Actually, to help organize this, I'm going to merge this into another branch on upstream. Will be easier for contributors to help us out that way as they can PR directly to that branch.

**Pull request merged**
