### PR TITLE
[WIP][Feedback Wanted]"Stop complaining about how difficult chess is, darling. I am going to teach you about this."

### PR DESCRIPTION
**Pull request by Wingdinggaster656**
Did you find that even after the difficulty of chess was reduced, you still couldn't win?
Do you see Monika saying the same line every time she win, and you get mad for this?
**_NOTHING TO FEAR FROM NOW ON! BECAUSE SHE IS GOING TO TEACH YOU ABOUT CHESS NOW!_**

Please let me introduce to you these chess lessons that I spent a few days to make!

### This Pull Request will contain:

1. The expected number of lessons is around 30, enough to take your chess ELO rating to around 1600 
    (Don't know what 1600 is? There is a reference, the level of beginners is 500 ~ 800). 
    See file _script-chess-lesson.rpy_.
2. A large number of chess puzzle sets that will be updated in future release like Fun Facts, Topics. See file _script-chess-puzzle.rpy_.
3. Dozens of chess points. It may also be updated in a future release, so make it a separate file first. See file _script-chess-point.rpy_.
4. A suggestion to let player get their "chess-personality", see www.chesspersonality.com

### However, this is not finished yet. I need help like:
1. Feedback. I assure myself that I have tested no performance problems, so the main thing I need is "educational" feedback. I wonder if these courses are really educational.
    Your feedback is really matter to me. I can not make this without any feedback. Since downloading these testing features won't do any harm to you, why don't you give it a try?
    Here's how to incorporate these testing features into your game:
    (1) Download these RPY files.
    (2) Copy them into your /game directory.
    (3) Open MAS. These files should be compiled into MAS now.

2.Code style optimization. I want my programs to run as efficiently as possible, so let me know if there's any code you think could be optimized.

3.Chess tutorial advice. My ELO rating is about 2100, which is good for the average person, but it's still dwarfed by real chess grandmasters. If there are any courses you think could be improved, please let me know.

4.How to implement the puzzle feature, which is still my consideration. This is a little complicated to explain, so ask me this if you know code, and I'll explain it in detail.

### Expected Completion Date:
Probably no later than 2021.07, most likely 2021.06.
To be precise, there is no "done" to this thing, and I will probably add more lessons in the future to try to bring players up to the level of ELO 2000. And these chess puzzles should be another updating-content in future versions, and there are endless puzzles to add.

##### Lessons:
- [x] What is Chess?
- [x] Pawns - Basic
- [x] Bishops - Basic
- [x] Knights - Basic
- [x] Queen - Basic
- [x] Rooks - Basic
- [x] King - Basic
- [ ] Pawns - Advanced
- [x] Bishops - Advanced
- [ ] Knights - Advanced
- [ ] Queen - Advanced
- [ ] Rooks - Advanced
- [x] PGN Standard
- [x] PGN Standard - Record a full game
- [x] Opening - Basic Idea of Openings
- [x] Opening - Sicilian Defense
- [x] Opening - Italian Game
- [ ] Opening - Queen's Gambit
- [ ] Opening - French Defense
- [ ] Opening - Modern Defense
- [ ] Opening - Center Game
- [ ] Opening - Scandinavian Defense
      (Not sure if we are going to add more openings now. I'm sure this is important and there will be more in future updates, but for now these major openings should suffice. )
- [x] Basic tactic - Forks
- [x] Basic tactic - Discovery
- [x] Basic tactic - Pin
- [x] Key Point 1 : Materials Value
- [ ] Key Point 2 : Position Value
- [ ] Key Point 3: Terms of Chess
- [x] Endgame - One Rook Mate
- [x] Endgame - Two Rook Mate
- [x] Endgame - Queen Mate
- [x] Endgame - Bishops Mate
- [ ] Endgame - Bishop and Knight Mate
        (The Bishop and Knight Mate is more likely canceled for now. While it may seem like another ordinary example of endgame, it's actually so horribly difficult that many grandmasters wouldn't even consider learning it.)
- [ ] Chess Nowadays(A brief introduction of the current chess community.)

##### Chess Points:
1. Openings - Sake for novelty
2. Principle Condition - "Usually so"
3. Openings - Some openings to beginners
(Only 3 points now. I guess I will extend this number to around 10 as this release's final result.)

##### Chess Puzzles:
Edit: I finally finished the chess puzzle system on 2021.07.12, though I don't really know how to list puzzles here. Should I just paste the FEN format string here to represent that puzzle? That would be strange.

Probably finished in no more than 7 days.

### CODE REVIEW

**Comment by catshift** [comment]
You did a good job, I am glad to be taught by Monika!

**Comment by lunulae** [comment]
I'm really excited to see this one finished, it looks like you have a lot of lessons I'm going to be interested in. Adding in puzzles is an especially cool touch.

I think it's a good idea to be able to review lessons you've already had. If I'm understanding correctly, it looks like the current format has them presented randomly like fun facts, but I'd like to also be able to select a particular lesson from a list if it's possible.

**Comment by multimokia** [comment]
Yeah I think having them work more akin to python/grammar tips would work best here for the lecture-style flow

**Comment by Wingdinggaster656** [comment]
> I'm really excited to see this one finished, it looks like you have a lot of lessons I'm going to be interested in. Adding in puzzles is an especially cool touch.
> 
> I think it's a good idea to be able to review lessons you've already had. If I'm understanding correctly, it looks like the current format has them presented randomly like fun facts, but I'd like to also be able to select a particular lesson from a list if it's possible.

See file script-chess-lesson.rpy,These lessons work like Python Tips and Grammar Tips. You can always review your lessons.
Maybe you could download these files to see.
As for Points and Puzzles, they are presenting randomly, this is true.

**Comment by Ant9cp** [comment]
Wow awesome man👍

**Comment by Wingdinggaster656** [comment]
I'm almost done, just need some instructions for the mainstream opening. Then, I was a little bit sad for lackin feedback. However, that's fine, after all, repeatedly backing up Persistent files is quite troublesome.

Well, anyway, I'm posting this comment to see if anyone can help me test their "actual usefulness". If not, that's fine, I'll find a friend to do it.

**Comment by Wingdinggaster656** [comment]
For "some reason" I decided to close the PR.
Don't worry, these classes are not canceled, I will open a new branch and start a new PR after I finish them.
I'm sorry if this has caused any administrative confusion.

**Pull request closed without merging**
