### PR TITLE
Room Decorations Code From LordBaaa

### PR DESCRIPTION
**Pull request by LordBaaa**
* Added sub_objects and weather_map as json parameters (with verification)
* Formatted code properly with full doc strings (up until now I was a bit looser with my formatting)

There is some art in the decorations folder that is just for testing, that is why it has words on it.
@tw4449 says he has a whole new room and non of this art will be part of his official thing so yeah that is just like testing art.

I don't really do pull requests often so let me know I messed anything up. Hope this is helpful, also some credit if this is implemented would be nice, I have been working on this for quite a while now.

Closing thoughts.
My next update will probably focus on more json stuff. I want to add in the in game night filter in to class. Atm it has code for using a special image for each weather such as what is required in @tw4449's art with the ability to expand to new weathers. But I want to set a parameter that tells if it should use special art or generate it automatically.
I really hope that after I create this pull request that you'll let me continue to work on this.

### CODE REVIEW

**Comment by multimokia** [comment]
Please resolve the conflicts

**Comment by jmwall24** [comment]
Something is wrong with this PR. it is showing not only your work, but almost everything we added in the last update as well. Also, when you open a PR you need to enable us the be able to make edits.

**Comment by multimokia** [comment]
You're going to need to extract your code from this and put it on a new branch. You updated your branch by replacing the files with stuff from the content branch. This overwrites the commit history and we cannot have that. You need to merge the content branch into your working branch to keep the commit history from everyone.

**Comment by LordBaaa** [comment]
Oh that is wierd it added in some artifacts like ====== <<<<<<< and stuff hold on...

**Comment by LordBaaa** [comment]
Did I do it right...?

**Comment by LordBaaa** [comment]
Also @jmwall24 now that I have made the PR how would enable write access for you?

**Comment by jmwall24** [comment]
@LordBaaa check on the bottom of the right bar of this PR, should be a box for `Allow edits for maintainers`

**Comment by LordBaaa** [comment]
@jmwall24 Okay it is checked

**Comment by jmwall24** [comment]
Thanks

**Comment by LordBaaa** [comment]
Hey fellas any progress on this? I want to keep coding but I don't want to make progress just to change it if you guys decided to change this code, as this is kinda my base. Please let me know if I can keep working on it and filling in some of the gaps that this code has. Thanks

**Comment by LordBaaa** [comment]
Alright then I’ll continue working on it. It was getting pretty good but there were still some features I really wanted to add.

**Pull request merged**
