### PR TITLE
New Past Relationships Topic

### PR DESCRIPTION
**Pull request by Rai99**
Issue: #2694 
This PR is waiting for #2575 as it uses sprites added in that PR. 
This PR in in conflict with #2719 as they both cover the same topic from the same request in the same issue.

The author of the issue requested that someone write a topic about this, but also created their own version of the topic as this one was in the process of writing. This was almost done before they put their version up. What else am I supposed to do?

### CODE REVIEW

**Comment by Bam8647** [comment]
Wow! You really went in depth Rai not bad! I really thought the responses leading into further conversations were pretty intriguing. You could possibly create a separate topic with how the player felt about their previous relationships compared to the player's relationship they have with Monika. 

I felt that there should only be three main responses to the initial question regarding dating. The responses are suppose to range from **Most Experienced to No Experience** so in this case **A lot** and **A few** could be combined as this already tells Monika that you've been through multiple break ups compared to just **one break up** and finally having **no experience dating** what so ever.

Again the extended conversations are a nice touch(: 
I just wanted to keep the initial dialogue short and to the point.
Don't get me wrong, new topics can be made from what you just made already which maybe we could figure out a second tier to the Dating topic so none of our hard work doesn't go to waste.


Anyways, Great Job!

**Comment by Rai99** [comment]
I was taking it easy, but you really made me speed it up with your PR.

**Comment by Rai99** [comment]
I hate to say it, but I don't think both of our PRs are making it in. I think yours might be the one that's taken since you got it up first.

**Comment by Rai99** [comment]
I felt that only having 3 responses (Multiple, one, none) left out a possible group. I intended the "A lot" option for those who basically have dating down to a science and it's nothing really special for them."I intended "A few" for maybe 2-3 relationships; More than one, but not enough to really have it come natrually. "Just one" of course, is unique enough to warrant it's own path and "None" is also a mandatory option. 

If the player has been in multiple relationships, they should be experienced and mature enough not to let breakups bother them, which is why I added much more in depth dialogue for the "one" option. 

I think we'll cross the bridge of what I'm supposed to do with my topic when we get to it. 

untitled1044

**Comment by Rai99** [comment]
This topic needs and rkbsa and rubfb for body pose 1.

**Comment by ThePotatoGuy** [comment]
okay need to figure out if this and #2719 can both be in or only one in.

**Comment by jmwall24** [comment]
Closing this in favor of #2719. This almost comes off as an interrogation rather than a conversation. Might put some people off.

**Pull request closed without merging**
