### PR TITLE
[Pool Topic] - Could it be? Writing Tip #6??

### PR DESCRIPTION
**Pull request by lunulae**
Was thinking about something I do for my own writing, and I thought it might make a decent Writing Tip of the Day. ✏️

### CODE REVIEW

**Comment by Wingdinggaster656** [comment]
You probably lost something.
Firstly, every writing tip ends like:
```
    m 3hua "...That's my advice for today!"
    m 1hub "Thanks for listening~"
```
Secondly, there should be a condition, like:
```

conditional="seen_event('monika_writingtip5')",
action=EV_ACT_POOL
```

**Comment by lunulae** [comment]
@Wingdinggaster656 Good catches, thank you~ Will add those in my next draft. ❤️

**Comment by Wingdinggaster656** [comment]
...Sorry, but I think your commit just lost another thing.
Did you forget ```prompt="Writing Tip #6",```?

**Comment by lunulae** [comment]
... omg, it was in the first draft, I dunno how it got deleted

**Comment by lunulae** [comment]
... wait a minute, now that just deleted a TON of stuff I didn't touch, what

**Comment by lunulae** [comment]
is there a way to revert a commit?

**Review by multimokia — APPROVED** [review]

**Review by jmwall24 — APPROVED** [review]

**Pull request merged**
