### PR TITLE
Update to kiss me topic

### PR DESCRIPTION
**Pull request by linkerplinker**
I halved the teasing option and made it more interesting i guess... Idk, I am planing on adding other topics to this relating to this.

### CODE REVIEW

**Comment by multimokia** [comment]
FYI that made teasing more common, not more rare

**Comment by multimokia** [comment]
Also, not all that fond of this dialogue compared to the old. Also, the didn't have first kiss yet option isn't supposed to have a sorta kiss in it at all.

**Comment by linkerplinker** [comment]
> Also, not all that fond of this dialogue compared to the old. Also, the didn't have first kiss yet option isn't supposed to have a sorta kiss in it at all.

back to the drawing board

**Comment by jmwall24** [comment]
Not sure you understand how quips work. It selects one of those lines at random, it doesn't go thru each line. Looks like you rewrote it thinking it'll go thru each line in order.

**Comment by linkerplinker** [comment]
> FYI that made teasing more common, not more rare

i didnt see it much and wanted to make monika more playful i guess

**Comment by linkerplinker** [comment]
> Not sure you understand how quips work. It selects one of those lines at random, it doesn't go thru each line. Looks like you rewrote it thinking it'll go thru each line in order.

aha i will change it

**Comment by jmwall24** [comment]
Also, you based this off of master branch, which is only updated upon release. Something like this should be based to content branch, which is updated more frequently. This branch is very outdated.

**Comment by linkerplinker** [comment]
> Also, you based this off of master branch, which is only updated upon release. Something like this should be based to content branch, which is updated more frequently. This branch is very outdated.

im getting used to renpy and github sorry

**Comment by ThePotatoGuy** [comment]
1. don't add unrelated things to a pull request unless the changes are dependent.
2. as mentioned above, quips are random selected and only 1 shown at a time.
3. you added a say after the kiss and before the "I love you" response menu. I don't quite get what the point of that is since the quip is already said after the menu.
4. You added a kissing sound and a chu in the not-kiss flow. That's literally subverting the point of that branch.

Overall, theres no enhancements in this pull request that are worth putting in even in concept. Closing.

**Pull request closed without merging**
