### PR TITLE
RenPy 8 / Python 3.9 migration 

### PR DESCRIPTION
**Pull request by Booplicate**
# Migration of our codebase to RenPy 8 / Python 3.9

We want to test #9742 first, it can be merged into `r7.4`, or into `content` after we merge `r7.4` there. But it should be ready when this PR is ready.

### Update changelog as you push!

<details>
  <summary>Changelog</summary>

### Code:
- Utilised some new config vars from r8
- `logging` has been updated to py3 (e.g. no more extra spaghetti to deal with newlines)
- Chess was updated for py3, improved `MASPiece`, optimised Monika's AI code
- Updated `MASFormatter` for py3/r8, slightly optimised
- Updated `mas_find_target` (part of our private API)
- `glitchtext` from DDLC was backported and optimised as `mas_glitchText`
- - `_mas_root.glitchtext` was removed as obsolete
- `pushEvent` > `mas_pushEvent`
- `queueEvent` > `mas_queueEvent`
- New store for overrides (?) `mas_overrides`
- Cleaned up cursed pong code
- Window reacts
- - Events now share rules (we copy the `dict`)
- - Events are marked with `restartBlacklist`
- Backported `ParticleBurst` from DDLC
- We don't check for DDLC rpa anymore
- - [ ] But maybe we should check for at least some?
- We now report why we had to reset outfit/hair
- Updated `_MASMoniFollowTransformDissolve`
- Backported poems:
- - `poem_m1` (Hole in Wall (Part 1))
- - `poem_m21` (Hole in Wall (Part 2))
- - `poem_m2` (Save Me)
- - `poem_m3` (The Lady who Knows Everything)
- - `poem_m4` (Happy End)
- Updated our custom updater code
- - [ ] Is it working?
- Updated our build
- - We're building our own executables now, we name them `DDLC` to obey the guidelines
- - Cleaned up builder massively
- - No longer use a custom package, instead build cross-platform "for market"
- - scripts are packed into `scripts.rpa`
- Updated persistent validation, we're using the compat code to be able to load py classes from py2
- Window utils were updated
- - Code cleanup, optimisation, and py3 migration
- - We're now caching `hwnd` on Windows OS
- - We're using `winnie32api` now
- - - MAS now always has tray icon (single) regardless of notifications
- - - - Clicking on the icon can clear notifs, set focus on MAS window
- - - MAS window can be flashed when sending a notif (a new parameter for the `mas_display_notif`)
- - Better x11/wayland check
- Old unused code removed
- - `MASMacLog`
- - `macLogOpen`
- - `getMASLog`
- - `logcreate`
- - `logrotate`
- - `mas_with_statement`
- - `MASImageData`
- - `Event.checkConditionals`
- - `Event.checkCalendar`
- - `Event._checkRepeatRule`
- - `Event.checkRepeatRules`
- - `Event.checkAffectionRules`
- - `Event._checkAffectionRule`
- - `MASInteractable`
- - `hideEventLabel`
- - `lockEvent`
- - `lockEventLabel`
- - `unlockEvent`
- - `popEvent`
- - `MASAffectionRule`
- - `grant_xp`
- - `get_level`
- - `mas_isMorning`
- - `mas_shouldChangeTime`
- - `_decide_filter`
- - `acs_lean_mode`
- - `clearUpdateStructs`
- - `getDayRoom`
- - `getNightRoom`
- - `unlock_selector`
- - `sp_window`
- - `isbg_window`

### RenPy script
- Removed the `mas_set_gender` label
- Removed/commented out `battery` related labels
- Backported styles from DDLC
- - `console_`
- - `poem_`
- Backported multiple DDLC transforms
- Backported poem images
- - `paper`
- - `paper_glitch2`

### Python-packages
- Removed py2 `logging`, renpy now includes `logging` by default
- Removed py2 `balloontip`, it didn't use winapi properly and required shipping extra libs
- Removed py2 `battery`, never worked anyway
- Removed py2 `eliza`, was unused
- Removed py2 win32api
- Added `unittest`, we can write proper unittest! Also useful for submods
- Added `winnie32api` my miniature wrapper around win32 api using `ctypes`

### Files
- Unused old icons
- - Removed `CustomIconMac.icns`
- - Moved and renamed `CustomIconWindows.ico`
- - - It's now `game/mod_assets/mas_icon.ico` and is used as the window icon as well as notif icon on Windows OS
- Backported poem words from DDLC
- - `game/mod_assets/games/hangman/poemwords.txt`
- Backported DDLC's `gui.rpy`

### Misc
 - Updated GH actions
 - - [ ] Update again to use the version we're going to stick for a while, instead of the latest nightly
 - Cleaned up gitignore, updated accordingly to the new repo structure
 - Updated `README.html`
 - - [ ] Requires to be updated again, r8 isn't a beta test, it's our main version
 - - [ ] Should also update `README.md`
 - Updated `project.json`
 - Removed `update/current.json`, it shouldn't be in the repo
 - Tools were updated to py3.9 and/or py3.10
 - - Some tools were removed as obsolete

</details>

## Testing:
 - TBA

### CODE REVIEW

**Comment by Booplicate** [comment]
I'll fill the changelog asap.

**Comment by ThePotatoGuy** [comment]
1. why aren't ghaction downloads being cached? cached stuff means faster builds and also wont raise a red flag to servers that may not appreciate constantly downloading source zips from (mainly renpy source).
2. this line is non-negotiable: `We don't check for DDLC rpa anymore`. There must be a hardstop if DDLC is not installed.

**Comment by multimokia** [comment]
I say we port DDLC's rpa check up to MAS level, however exclude `scripts.rpa` from the required set. Then, we rename `scripts.rpa` to be non-loadable

**Comment by ThePotatoGuy** [comment]
hmmm ok I'll check these conflicts out, then approve this to go in as long as it runs. 

that'll make it easier to solve the remaining outstanding boxes on the py3 prep as the major stuff is in

**Review by ThePotatoGuy — APPROVED** [review]
aiight

**Comment by ThePotatoGuy** [comment]
@multimokia @Legendkiller21 yall still around ?

**Review by ThePotatoGuy — APPROVED** [review]
lol forgot that commit

**Review by ThePotatoGuy — APPROVED** [review]
(tested that it runs and persistent loads) twice

**Review by ThePotatoGuy — APPROVED** [review]
tested the following:
* loading v12.12 persistent with game/saves deleted - v12 persistent was loaded
* loading v13 backup persistent - backup persistent loaded
* loading v13 normal persistent - normal persistent loaded

**Review by multimokia — APPROVED** [review]
Screm

**Pull request merged**
