### PR TITLE
Fixed text display when gifting Just Monika thermos

### PR DESCRIPTION
**Pull request by WishStone-Dragon**
The fix changes how the text behaves when the thermos is gifted. 
Using the old "capitalize" command, the text delivered reads:
`Oh! A just monika thermos!`
The change to "title" changes how this text behaves into:
`Oh! A Just Monika thermos!`
title
capitalize

### CODE REVIEW

**Comment by Booplicate** [comment]
Thanks for your contribution! It's nice you found this "typo", but I don't think I like this approach. One problem is in the `elif persistent._mas_given_thermos_before` path the issue still persists. But also, I think we should fix `mas_a_an_str` (alternatively - use another function for this) rather than working around it.

**Comment by WishStone-Dragon** [comment]
This is what happens when a newbie tries to mess with things...
Should I change to the fix you noted, or let a professional handle that? :3

**Comment by Booplicate** [comment]
You absolutely can do this!

First you will need to rebase your PR to the `content` branch.

**Comment by WishStone-Dragon** [comment]
Hm. I just did a test-run for the suggested change (just removing the .capitalize() in the code). Not sure this is the desired result, however. See picture.
image

Now I am starting to wonder if it could be easier to simply change what she says. 
`m 1wud "Oh!{w=0.3} [mas_a_an_str(disp_name, ignore_case)] thermos!"`
to
`m 1wud "Oh!{w=0.3} It's [mas_a_an_str(disp_name, ignore_case)] thermos!"`

**Comment by WishStone-Dragon** [comment]
I'll see about getting help. Like I said, noob, no idea how most of this works. Not yet found out how to do the rebase (while having no idea what that even means x3).

I will update when I can.

**Comment by WishStone-Dragon** [comment]
Okay, first the good news: Just changing that text a little bit looks fine after removing `.capitalize()`!
Now, let's see how I can get this in here.
image

**Comment by Booplicate** [comment]
@WishStone-Dragon [check this](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines#your-first-contribution).

**Comment by WishStone-Dragon** [comment]
Thanks much, and I know you mean well, but you overestimate a bit on how much lift these documents bring for someone who has _literally_ no coding experience. Frankly... they do not explain to me what I need to do.

I'll be getting with a friend who can try to figure out what I need to do next. If this blocks anything, simply close this and I will maybe try at a later time.

**Comment by Booplicate** [comment]
There's the edit button at the top, press it. Then you can select a new base branch. You want `content`.
Capture

**Comment by WishStone-Dragon** [comment]
Hecc, never saw that. 
But I also need to somehow... fix this. Like, the submission itself does not have the fix in it, see?

**Comment by WishStone-Dragon** [comment]
Hm. When I go to try and edit the code to reflect the change, it insists on staying in Master...
image

**Comment by Booplicate** [comment]
It says `master` because you based your work on *your* `master` branch and made the changes on *your* `master` branch. Usually you want to make a new branch for new project/fix/PR/etc. But for now it's fine if it stays `master` there. So long as the PR is based to `content`. That's the branch where we'll merge your changes to.

**Comment by WishStone-Dragon** [comment]
I BELIEVE I made the changes you requested to the file and the rebase. 

---

Wish now learned how to make branches so this won't happen again.
Super-sorry for my dust. I had two folks on Discord talk me through some of this and they are the best.

You'll notice I made no changes to the other line containing 'elif persistent._mas_given_thermos_before'. In this case, the bug didn't show itself, as it wasn't the start of the sentence. This issue only crept up, because:
'm 1wud "Oh!"' ended the sentence.
'm 1hua "And it's [mas_a_an_str(disp_name, ignore_case)] one this time."' here the line wasn't interrupted by the exclamation point (or other sentence-ending indicator).

**Comment by WishStone-Dragon** [comment]
Wanted to follow up, where were the changes made acceptable?
If not, I can close this out and try a new submission following the correct branching process.

**Comment by Booplicate** [comment]
I might just merge this into typos, actually. Or maybe just merge this, will see.

**Comment by WishStone-Dragon** [comment]
Feel free to lift and steal it, too. I am not married to this. Only wanted to pitch in. x3
Thanks for all your help! Will try to make the next one less work for you.

**Comment by Booplicate** [comment]
Don't worry, even if we only moved the commit, you'd still be credited as it's *your* commit.

**Review by Booplicate — APPROVED** [review]

**Comment by Booplicate** [comment]
@ThePotatoGuy this is smol, give it a look when you have time. I tested, works fine.

**Review by ThePotatoGuy — APPROVED** [review]

**Pull request merged**
