### PR TITLE
Fixed multiple crash greetings on startup crashes

### PR DESCRIPTION
**Pull request by multimokia**
If you crashed after init, it was possible that crash greets would keep queuing and queuing, effectively having them repeat. This should make sure we only get one crashed greet, and one force close (just in case)

## Testing:
I find the easiest way to verify this is to head into `mod_assets/monika/` and then rename the `c` folder. Please first verify that on a normal install without this code in it the crashed start greet stacks by opening the game, getting the traceback, then exiting. (Repeat a couple times)

Once done, please then verify with this code that you only get a single crashed start greeting by once again launching, getting traceback, quitting, and then doing that again a couple times.

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
does the restart blacklist not work for this?

**Comment by multimokia** [comment]
Didn't seem to, I've managed to get numerous crash greetings in a row in the past, and seems a user in #tech-support did too.

**Comment by ThePotatoGuy** [comment]
let testing happen on this, but I want to make sure we know why the restart blacklist isnt working here before merge.

**Comment by multimokia** [comment]
Sounds good

**Comment by multimokia** [comment]
Below is why the restart blacklist didn't work:

The restart blacklist never worked as intended, it was merely checking the `persistent.current_monikatopic` to see if that should be restarted via `continue_event`, however it never cleaned the `persistent.event_list`.

The changes here now add a function which cleans the `persistent.event_list` for all topics which shouldn't repeat upon reload.

**Comment by ThePotatoGuy** [comment]
>The restart blacklist never worked as intended, it was merely checking the `persistent.current_monikatopic` to see if that should be restarted via `continue_event`, however it never cleaned the `persistent.event_list`.

This is how the blacklist intended to work. However it does make more sense to clean the entire list when starting.

**Pull request merged**
