### PR TITLE
I don't want to be Mean to her.

### PR DESCRIPTION
**Pull request by linkone2**
A small addition to the "You're a murderer!", "Do you want to meet my girlfriend?", and "I'm breaking up with you" topics, so that they go away after you reach Enamored+ (400+). 

I tested it by going through the affection levels and seeing if the topics were there, like this: 
(AFFECTIONATE) 200 (There) > (ENAMORED) 400 (Gone) > (LOVE) 1000 (Gone) > (ENAMORED) 400 (Gone) > (AFFECTIONATE) 200 (There) > (HAPPY) 50 (There) > (NORMAL) 0 (There) > (UPSET) -50 (There) > (DISTRESSED) -75 (There) > (BROKEN) -100 (There)> (AFFECTIONATE) 200 (There).

### CODE REVIEW

**Comment by Rai99** [comment]
Hold on a second. I don't think this should be forced on everyone. Sure, most people probably wouldn't use these at high affection levels, but part of the charm of MAS I think is that it's possible to be mean to her. MAS wouldn't be as in depth if being mean wasn't an option, and with this, it'll be much harder to go down after reaching those aff levels. 

It's already much easier to gain aff than lose aff at those levels, so I think completely removing those topics seems unnecessary. 

This probably falls under exclusion/favorite menu: #959, #1405, #2047, #2094, #2156, #2730, #3022, #3594.
It's low priority at the moment, but I think it'll help sort out this issue with not wanting the mean topics. 

Also, I'm actually working on April fools day interactions on those very 3 topics, so there might be a small problem there. 

Also, this PR is going to master. ~~Put your hands behind the ground.~~

**Comment by Rai99** [comment]
One thing's for sure though, your PR probably shouldn't be aimed at `master`.

**Comment by jmwall24** [comment]
ehhhh, people can break-up who have been seriously in love. not sure i agree with limiting this by affection.

**Comment by Rai99** [comment]
If anything, I think the solution would be to make it so you can't accidentally click those options, but not completely remove them.

**Comment by multimokia** [comment]
Agree with this. I don't see why removing the idea of breaking up makes sense, as anyone *can* break-up at any time, really. No matter how in love they may be. Realistically, just changing their unseen status would do the trick.

**Comment by multimokia** [comment]
Leaving `Don't Merge` as I'd like some internal discussion on this.

**Comment by multimokia** [comment]
Yeah, we're not going to do this. Closing.

**Pull request closed without merging**
