### PR TITLE
New pool topic - Why spaceroom?

### PR DESCRIPTION
**Pull request by LooseEthics**
Based on one of the responses to #5764.
Asking Monika why our interactions take place in the spaceroom.

### CODE REVIEW

**Comment by satoshi-kun** [comment]
Hello!
Sorry to barge in but isn't Monika using the bedroom aswell?
When you start the game and the door is closed Monika will appear standing in the bedroom, if you choose the option of opening the door without knocking first.
Just thought that maybe that should mentioned.
Otherwise it seems great! Thanks!

**Comment by LooseEthics** [comment]
The bedroom exist, but there isn't a whole lot happening there. I don't think you even get to see it unless you barge in. Vast majority of interaction takes place in the classroom. 
This topic is meant to address why that's the case, as opposed to using the bedroom or any other location.

**Comment by satoshi-kun** [comment]
I understand that but it just seemed a bit off when it is said "It hasn't really occured to me to move someplace else until now", since she apparently also spends some time in the bedroom while the player is out. And even if the player knocks on the door and doesn't get to see the bedroom, it is given the impression that she wasn't at the spaceroom at that time as she states that she needs to grab the table and chair beforehand.

**Comment by lunulae** [comment]
I think, though, with the bedroom, Monika implies a desire to have a private space for herself. Spending time  together there wouldn't be impossible, but it probably wouldn't be her preference right now.

**Pull request merged**
