### PR TITLE
Added more bad nicknames

### PR DESCRIPTION
**Pull request by LordDemecrius83**
Ignore the "wtf is this commit" ,It was added by accident

### CODE REVIEW

**Comment by Wingdinggaster656** [comment]
_I must say that I laughed at `cpu eater` the name_

Why `kkk` is a bad name?

**Comment by Wingdinggaster656** [comment]
_I must say that I laughed at `cpu eater` the name_

Why `kkk` is a bad name?

**Comment by LordDemecrius83** [comment]
> _I must say that I laughed at `cpu eater` the name_
> 
> Why `kkk` is a bad name?

short for Ku klux klan

**Comment by Wingdinggaster656** [comment]
> > _I must say that I laughed at `cpu eater` the name_
> > Why `kkk` is a bad name?
> 
> KKK is short for Ku klux klan

I think we should not block `kkk`. That's overkill. And, maybe `cpu eater` should be an awkward name, not a bad name, since it was more or less a joke.

_And by the way if we eventually add `cpu eater` , let us also have `gpu eater` lol_

**Comment by LordDemecrius83** [comment]
> > > _I must say that I laughed at `cpu eater` the name_
> > > Why `kkk` is a bad name?
> > 
> > 
> > KKK is short for Ku klux klan
> 
> I think we should not block `kkk`. That's overkill. And, maybe `cpu eater` should be an awkward name, not a bad name, since it was more or less a joke.
> 
> _And by the way if we eventually add `cpu eater` , let us also have `gpu eater` lol_

Fair enough

I'm also working on fixing window reactions on GNOME but I've made no progress the game would either crash or throw an ignorable exception

**Comment by Booplicate** [comment]
Please keep commits related to the PR, if you want to fix something else, open a new PR.

**Comment by Booplicate** [comment]
Are you cosplaying Rai.

**Pull request closed without merging**
