### PR TITLE
Added timed menu to comfort Monika when she cries

### PR DESCRIPTION
**Pull request by Rai99**
I had this idea before the issue was brought up, but this kind of addresses #2267 for being able to do something when Monika tears up a bit in this topic.

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
The `hug monika` menu choice doesn't seem like a good idea to use. The concept of using the menu buttons as actions should only cover meaningless actions (like how the crash greeting does "turn on the light"). Hugging is more a connected action and having it as a button action devalues its impact.

**Comment by Rai99** [comment]
I was thinking that directly hugging Monika here would be a common option to calm her down. It's a serious moment, so I thought hugging Monika would be a justifiable option here. This event should only be available to the player at affectionate and above, so the player could just ask Monika for a hug anytime anyway, which would probably have less impact than hugging her in this moment. 

If the problem is that hugging Monika was directly put in a menu option, I could add some lead in to the hug instead of doing it instantly by surprise, but I think instantly hugging Monika in that situation fits the mood.

**Comment by AsuraShun** [comment]
maybe dry her tears and a kiss to the forehead would help,don't know if it would be possible though

**Comment by Rai99** [comment]
One of the harder parts of making things like these is finding the right sprites that actually exist and are ready for use, so I'm not sure if dry tears have any fitting, usable sprites. 

I would have loved to add an option to kiss Monika on the forehead, but I'm not sure if that could be well done with the resources available at the moment. It might be doable, I just thought that kissing Monika should have some unique sprites. In this scenario however, it might just work with what we do have.

**Comment by AsuraShun** [comment]
as long as it's possible to comfort her somehow, i don't really care how as long as she's happy

**Comment by AsuraShun** [comment]
YUS!

**Comment by Rai99** [comment]
Somebody seems happy

**Comment by dennisOdenbreit** [comment]
> The `hug monika` menu choice doesn't seem like a good idea to use. The concept of using the menu buttons as actions should only cover meaningless actions

The only way for the player to interact with monika on their initiative should consist of meaningless actions?

**Pull request merged**
