### PR TITLE
Add 5 topics,1 question to ask.

### PR DESCRIPTION
**Pull request by Wingdinggaster656**
Just like the title. As for more details, I think my commit names would do the rest.
I ran the test on my own device, it's not like there is a program bug. But since I am not that familiar with these formats,I think there are typos.
Any suggestions will be nice to me.

### CODE REVIEW

**Comment by Wingdinggaster656** [comment]
Oh, by the way, my English is not very good, maybe there are some grammar mistakes.

**Comment by multimokia** [comment]
Please split topics into separate PRs, it makes them easier to review, especially if there's some which may not fit and need to be removed/need large changes/etc.

**Comment by Wingdinggaster656** [comment]
> Please split topics into separate PRs, it makes them easier to review, especially if there's some which may not fit and need to be removed/need large changes/etc.

Got it. So should I close this pull request and create 6 new PRs for 5 new topics and 1 new question now?

**Comment by Booplicate** [comment]
Leave 1 topic in this PR and move the rest 5 to their own PRs.

**Comment by Wingdinggaster656** [comment]
Close as I didn't notice that 5 topics should have 5 PRs.

**Comment by 20RaVen23** [comment]
No need to close it, as the comment from Booplicate said, leave one topic on this one, which implies to leave it open

**Pull request closed without merging**
