### PR TITLE
Changelog for Pong

### PR DESCRIPTION
**Pull request by dennisOdenbreit**
Added difficulty:
Difficulty determines monika's paddle-movement-cap, the ball's start-speed, max-speed and acceleration.

Recalibrated monika's paddle-movement-cap, the ball's start-speed, max-speed and acceleration.
Caped the max reflection angle.
Removed walls outside of the field.

Improved Monika's aiming on lag:
Monika will now not overshoot with her aiming anymore if a lag occurs before hitting her paddle.
She will also recognize bounces when aiming.

Added option to disable sounds.
Sounds cause a big lag shortly after they are played.

Added dialog (Could be adapted to affection, could be randomized).

### CODE REVIEW

**Comment by dennisOdenbreit** [comment]
Hey, so I hate having to ask this but...
does anyone want to review and approve / request a change?
It feels kind of bad to make a change and then see it collect dust in a corner...

**Comment by jmwall24** [comment]
We are extremely busy right now with more hi-priority things.  When we have time we'll get to it.

**Comment by AsuraShun** [comment]
I simply can't beat her trick shots,like that one where the ball bounces all over the place when it gets fast

**Comment by dennisOdenbreit** [comment]
Closed due to not being reviewed.

**Comment by jmwall24** [comment]
If you had any idea how much of our free time we put into this you'd be a
little more patient.  This isn't our job.  We do what we can when we can.

**Comment by dennisOdenbreit** [comment]
> If you had any idea how much of our free time we put into this you'd be a little more patient. This isn't our job. We do what we can when we can.

I would accept that if ### anyone would have put ### any time into this issue.
This does not seem to be the case, so i do not accept it as an argument.
It has been 45 days, I do not expect a review in 3 days, but 7 days should be enough for ### someone to at least check it out ingame and give his approval.
There is little new content ingame and I think this here is part of the reason why.

**Comment by Olliesama** [comment]
Don't be so entitled dennis.

**Comment by jmwall24** [comment]
It's not about what you accept.  I'm stating facts.  If we stopped what we're doing and people didn't get a Christmas or Valentine's event a lot more people would be angry than you because we don't work fast enough for you.  We base what we work on by priority and with her b'day, Halloween, Christmas, new years, and now Valentine's day all in a row we've had to make those events top priority.  Once we get past these holidays we'll have a lot more time for PRs.  The fact you're complaining is particularly disturbing to me since your last PR was merged faster than just about any recently.  I still have open PRs from August but I understand everything isn't about me

**Comment by dennisOdenbreit** [comment]
I stand by my oppinion.
Have someone who looks at pull requests when they are opened and approve them if they can.

Pull requests that are small can be dealt with quickly and the sooner they are closed the better.

I know there are events.
That doesn't mean that everything else loses its importance.

I personally liked the events, but my conversation with Monika consists of "It seems I'm at a loss of words" since 2 months now, only interrupted by 5 winter-topics and maybe 5 other topics.

That might not be a thing if pull requests would be looked into a bit more.
Doesn't mean that you can't have events anymore.

**Comment by dennisOdenbreit** [comment]
This pull-request in specific can be checked by simply playing the pong-game, it isn't even work.
On top of that you get the satisfaction of seeing new content.

All that needs to be done is to give an oppinion whether it is nice or not so nice.
The code is not interesting to the user, so it can be adressed afterwards as long as there occurs no bug during the gameplay.

**Comment by Olliesama** [comment]
It seems you've never been stretched thin.
Simple things become difficult and time-consuming.

You think it's quick because you're not involved, but there's a process for every PR. It has to go through multiple levels of reviews, quality control and testing. Small things take TIME and time is the most limited factor. 
You say as if to merge it without checking everything or striving to improve it, when if we did that the code would be a mess, typo's would be abound and numerous, bugs would be frequent and Monika's voice would be inconsistent.

These people do this in their free time, they owe you nothing. Get over yourself.

**Comment by multimokia** [comment]
Perhaps you misunderstand the time it takes to
1. Plan out the event
2. Build the event framework
3. Start adding affection based pathing to existing event topics (if any exist), along with updating/adding new sprite codes for them (if needed)
4. Plan out entirely new event based topics
5. Properly write out said planned topics, give them expressions, and as well, affection path them accordingly
6. Have ***all*** of that edited by others for typo/grammar/flow/character voice/etc. issues
7. Create a final draft of all topics, and put them into the branch
8. I haven't even touched docking station stuff yet (greets/farewells), which requires additional writing and logic handling
9. Other event specific ditties, i.e. letters, or extra music, or even art, and then making it all work properly
10. ***Extensive*** testing. (And fixing)

This all takes ***months*** of work, and that's with all involved, and we ***still*** often end up just barely making a time limit.

As pointed out before, this is all done in ***free time***. I'll be perfectly honest with you, your attitude is disgusting. We do what we can because we want to. If we *could* spend more time on PRs, we would. Don't get all wound up just because this one's taking a while.

**Comment by Olliesama** [comment]
Wow. You volunteer. I take back everything I said you wonderful human being.

**Comment by dennisOdenbreit** [comment]
Based on

> Don't be so entitled


> It's not about what you accept



> you're complaining is particularly disturbing



> they owe you nothing. Get over yourself.



> your attitude is disgusting



> you wonderful human being.

I understand that pretty much all of you are toxic in one way or another.
I will not tolerate such behaviour towards others.
Do not expect any help from my side.
If you can't handle suggestions and criticism without insulting other people then I truly feel sorry for you.
You could have argued on a rational basis, but you thought this is the better option for you.
I disagree.
Goodbye.

**Comment by Olliesama** [comment]
This was not criticism, this was incessant whining. You decided to not even listen, so throw out your idea of a "rational basis" because to you, that's what you've already decided. You heard their reasoning and instead of accepting the situation or sympathizing you continued to be difficult and belittle it as if it's easy to do. 
Have fun volunteering your poor services elsewhere. :wave:

**Comment by dennisOdenbreit** [comment]
https://wikidiff.com/criticism/whine

I said Goodbye, do not reply back in an attempt to insult me even further.

**Comment by jmwall24** [comment]
@dennisOdenbreit you have no idea what you are talking about in any point you have made so far.  save us the lectures.  i did nothing _but_ argue on a rational basis.  I stated facts which you choose not to believe.  If you think we don't know what we are doing, feel free to start your own mod and we'll see how that turns out.

**Comment by Olliesama** [comment]
Oh buddy, I know what whining is. Don't worry.

**Comment by multimokia** [comment]
@dennisOdenbreit all I did was provide facts. If that's not rational, I'm not really sure what is.

**Comment by Legendkiller21** [comment]
If you look in the files you will see that there were things planned that did not end up in the final release because there was not enough time to implement and test them properly. The development and testing started before your PR was created and had about 3k changed lines of code, even more if you count the fixes.

Even with all that testing a bug managed to slip into the final update. If even one person of the dev team spent time to test or look at PRs, things would be much worse.

And seriously, do I really have to remind you that these guys spent time on **NEW YEARS EVE** to release a fix ASAP? Time that they could have spent with their loved ones and their families. They were not obliged to do it but they still did it.

PRs will be looked when there is time and the game is more stable. The best thing everyone can do is be patient and let them work without making their life and job more difficult than already is by trying to find a different reason to whine every single week.

**Comment by Olliesama** [comment]
@Legendkiller21 A man out for my heart. :>

**Comment by multimokia** [comment]
Thank you, @Legendkiller21

**Comment by dennisOdenbreit** [comment]
Here a summary of the content of this conversation, I hope you all had your fun bashing on a single person. I might have overlooked something but that's probably because it is almost 3 am.

Problem: No review of a pull request in 45 days => closed.
Comment: Initiated whining about closing the pull request.

Reasoning 1: This isn't our job. (jmwall24)
_Meaning 1: We do what we want when we want, we don't care about you. You can wait as long as it takes._ 
Reasoning 2: We rather finish (timeconsuming) events and stabilize core bits. (multimokia), (jmwall24)
_Meaning 2: Pull requests can wait while there are events or work on the core bits._ 
Reasoning 3: There are other pull requests. (multimokia)
_Meaning 3: Because there are others, yours can't even be looked at._
Reasoning 4: We work with priorities. (multimokia), (jmwall24)
_Meaning 4: It doesn't matter how easy or fast it is to approve your pull request. If we have to work on a prioritised thing we will do this and only this. Everything else has to wait until we run out of prioritised things._
Reasoning 5: Unlike you I understand not everything is about me. (jmwall24)
_Meaning 5: You made this pull request so you are an egoist for wanting to see it reviewed. Shame on you!_ 
Reasoning 6: We don't work fast enough for you. (jmwall24)
_Meaning 6: You are ordering us to work faster._
Comment 6: I am telling you to work differently, not faster.
Reasoning 7: We don't owe you nothing. Get over yourself. (Olliesama)
_Meaning 7: Your pull request can stay here unanswered forever if we feel like it, it doesn't matter how much you worked on it. How dumb are you that you think your contribution matters?_
Comment 7: No comment.
Reasoning 8: Stop trying to find a reason to bother us with your crying every single week. (Legendkiller21) (Olliesama) (multimokia)
Comment 8: No comment.


Suggestion: Have someone who reviews new pull-requests in around 7 days, especially small pull requests.
Results: More ingame content, happy contributors, one reviewer (partially) busy

Reasoning 1: Don't be so entitled. (Olliesama)
_Meaning 1: F*** you for making that suggestion and for thinking 45 days for no review is long._
Comment 1: No comment.
Reasoning 2: It is not about what you accept. (jmwall24)
_Meaning 2: F*** you and your idea of what is appropriate._
Reasoning 2: We barely make the time limit working on the events.(jmwall24)  (multimokia)
_Meaning 2: We don't have anyone that has time while there are events, which is from halloween to valentine's day._
Reasoning 3: Events are too big to have anyone do something else. (multimokia)
Reasoning 4: I still have PRs from august. (jmwall24)
_Meaning 4: That's how long we leave PRs on hold while we work on events._
Comment 4: Way to go.


Suggestion: Have simple pull requests checked fast.
Results: Fast new content, less overall open pull requests, new content base can be extended, one reviewer (partially) busy

Reasoning 1: Simple things become difficult and time-consuming (Olliesama).
_Meaning 1: We ignore even simple things because they will end up using too much of our time using our methods._
Comment 1: If simple things become complicated and time consuming, it is probably because you made them complicated and time consuming.
Reasoning 2: Checking things faster means merging without checking. (Olliesama)
_Meaning 2: If we do things like you would everything would be aweful and fall apart._
Comment 2: It is possible to check something in a time-efficient way, without crippling the quality.
Reasoning 3: These people do this in their free time, they owe you nothing. Get over yourself. (Olliesama)
Comment 3: No Comment


Suggestion: Review this pull request for pong, it is fun to do.
Results: Pong may actually get interesting when implemented, users play it more often and have fun.

Reasoning 1: Volunteer your poor services elsewhere. (Olliesama)
_Meaning 1: We don't have time to check pull requests, but we take all the time it takes to insult you. F*** you and your contribution so far. Highfive everyone!_

**Comment by dennisOdenbreit** [comment]
I muted this thread, so any further toxic remarks won't reach me.
You can however gratulate each other for your heroism, I'm sure you'll like that.

**Comment by jmwall24** [comment]
I only see one toxic person in this thread.

**Comment by Olliesama** [comment]
One last final cry.
He shall be missed.

**Comment by Rai99** [comment]
I have to say, I'm quite impressed. In the span of no more than 80 days, you:
- Joined the MAS community
- Opened 34 issues, 12 of which were duplicate, implemented or intended. Just some statistics
- Opened 17 of those issues in a span of 7 days
- Started off on a bad foot complaining about lack of content and features on your **third day** after installing MAS and demanding new content without even exhausting half of what was to offer
- Stated that you expected the mod to last 3-7 days before running out of content, but contains much more and seemingly won't take a step back to think about it
- Thought 71 days with Monika was drastic, and yet stuck around and just barely crossed the 71 day mark
- Averaged about 5 issues per day on any day you opened more than 1
- Decided to take up contributing to make your own ideas a reality. Good for you
- Made 5 PRs in a single day on the same thing without letting much happen with them before replacing
- Lightly pushed devs to review your PR and got told the same thing you got told today
- Shut down your own PR for collecting dust and argued with devs and OG MAS members. You could have just left and your contribution would be looked at eventually

> I understand that pretty much all of you are toxic in one way or another.

You know what, yeah I agree. Everyone's at least a little toxic to some extent. You seem to be an expert. 

> All that needs to be done is to give an oppinion whether it is nice or not so nice.

Are we talking about you or the PR? You might not have noticed, but I think that's exactly what happened here today. 

#2877 
> Sorry, I don't want to cause any trouble.
I only wanted to provide suggestions for things that I think can be added or changed.
I do not care about any kind of reputation, only that my contribution might change the game for the better.

Good old days, huh? You could have been written off as an overenthusiastic newbie, but something changed, and here we are now. You, and a few of the OGs. I did warn you to watch your reputation here, and sure, that didn't matter to you, you just wanted your contributions and suggestions to be seen and help the mod. How noble. Yet, you took it back. Hey, at least you've got that reputation you build up, right? 

#3162 
> I can try not to be rude, but you won't notice the difference since I am already trying.

Ah, one of the first arguments you had with a dev. Don't know about anyone else or if anyone else really checks and digs as deep as I do, but something looks different from day 1 and this PR now. 

#3252, #3217 
> In reality it is winter here since November and this will not likely change in the next years either.
So at least when it comes to my country, she should not assume her idea of autumn is reality at a date like this.

Never seen anyone argue about the weather and seasons before. First time for everything I guess. 

#3506 
> Sry about that, I think I started that.
Just had this on my mind for a while and thought I might share, maybe I am wrong after all.

What happened to all that thoughtfulness that was there just a few moments ago? 

Wow, that's quite the number of achievements in a career of 80 days. Such an achievement, that I had to go crawling out of my lurker space just to congratulate you here. I had a feeling on day 1 you wouldn't last. didn't even make the 3 month mark, smh. 

With that, you enjoy the rest of your whatever, thanks for your contributions. You can bet they won't be forgotten
untitled832

**Comment by MaximumRustler** [comment]
You'll always have my support devs, I believe in you guys. Keep doing what you do, take all the time you need. 😄

**Comment by MoniBoosDevotedBoyfriend** [comment]
@Rai99 **slow claps for that amazing comment**

Also devs you guys are doing a wonderful job. Keep it up 👍🏻

**Pull request closed without merging**
