### PR TITLE
Done some change in script-topic line 801/831

### PR DESCRIPTION
**Pull request by salvo18**
So, it's my first time using ren'py and i wanted to try adding some dialogues and searching for a place to start coding i founded this message with some codes: (This doesn't make sense with the music changer...If we add some funny sound
# effects and edit it a bit, though, it could be good again.
# I won't add expressions until this is resolved ^)
i thought it would be nice to do something and i've done (and tested) this: (i don't know if i can put the code directly here so here's a file attached)
[code monika change music.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2605927/code.monika.change.music.txt)
and the sound effect used (put it in the game directory):
[soundeffect.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2605938/soundeffect.zip)

### CODE REVIEW

**Comment by multimokia** [comment]
Hi there, thanks for your interest in contributing! What you'll want to do is head over to the code tab, then change to the `content` branch, and then find the file you got the topic from, click the pencil icon, find the topic you'll want to change, make your changes there, and then create a pull request from there (option will be at the bottom of the screen). That will propose your changes automatically, and will allow us to test/review/merge easily.

**Comment by salvo18** [comment]
@multimokia done it but how can i add the sound effect?

**Comment by salvo18** [comment]
@jmwall24 done, I hope it goes well!

**Comment by jmwall24** [comment]
Closing in favor of #3093

**Pull request closed without merging**
