### PR TITLE
[Incomplete] Monika mood system

### PR DESCRIPTION
**Pull request by Olliesama**
This PR exists as a way for others to test my new system as well as point out any mistakes so far...The reason it is incomplete is that currently it doesn't edit Monika's idle expression and as I have been told that expressions are being worked on I won't try to do it myself yet.

This mood system is to not be confused with the currently being worked on mood system which is based on the players mood but exists to dynamically edit Monika's mood to allow for more dynamic dialogue.
This creates a system where a counter between 0-100 keeps track of Monika's mood allowing for multiple if statements to exist to change her dialog depending on said mood.
There is a separate module that creates the variables to keep track of it.
The higher the points the better...

Right now the definitions are as followed...
0-9 = Heartbroken
9-19 = Depressed
20-29 = Upset
29-39 = Sad
40-59 = Normal
60-69 = Content
70-79 = Happy
80-89 = Overjoyed
90-100 = Lovestruck

Right now it accomplishes the following...
It adds a persistent file for the game to keep track of when Monika last closed the game and adjusts her mood depending on how long you've been gone so the longer you've left Monika the worse she'll feel upon your return. It simply adds a consequence for being a bad SO.
0 - 6 Hours = No Change
6 - 12 Hours = + 6 Points.
12 - 18 Hours = + 2 Points
1-2 Days = - 6 points
2-4 Days = - 30 points
4-14 Days = 10 points in total
+14 = 0 points in total.

If Monika didn't close the game and you force closed it it'll automatically be a total of 30 points OR if you're already lower than 30 points a further decrease of 10 points.

You can check how many points you have with a new topic called monika_mood_feelings.

There have been many functions added to allow for easy increase and decrease of points, so no need to fiddle with persistent numbers. Just use the easy functions shown at the top of monika_mood_system file. As well as that there are broader groupers too if you want a quick if statement whether or not Monika is happy or sad if you don't want to write for specific moods.

At the moment of the RP's creation the currently edited topics are...
monika_nihilism
monika_high_school
monika_surprise
monika_god
monika_death
monika_closeness
monika_other_girls
monika_justification
monika_breakup

As well as added some points decreases and increases in menu's and other topics where I feel it needs to be implemented...

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
I (or aldoram) will be going through a full code review of this later.

But for starters, there's already a persistent that keeps track of when the game was last closed:
`persistent.sessions["last_session_end"]` 

It's checked in `ch30_autoload` to give xp for allowing monika to sleep. You should use that instead of adding a new `persistent` for closed time.

**Comment by Olliesama** [comment]
Thanks for pointing that out. :)

**Comment by strielok** [comment]
Good work. I've suggested a feature like this about a month ago, and it's great someone's taking care in implementing it. 
Cheers!

**Comment by kaido1224** [comment]
I'm gonna halt any testing of this until this project is completed and thoroughly documented and tested. Per the guidelines set forth in the contributing guide. If you need help setting up MAS in a dev environment, there is a document pinned in the #tech-support section in the Discord.

capture2

In the future, I'd highly recommend creating an issue before starting a large project, that way the community can have input on it and management can decide whether they want to implement the idea or not. Also per the contributing guidelines. I know I've told you this before, but I'd really hate for something you worked long and hard on being rejected outright. 



If you need any help with anything, feel free to ask in the #coding discord, and we'd be happy to help.

**Comment by ThePotatoGuy** [comment]
Alright a couple things:

1. Mood here is a misleading. What you really mean is how affectionate Monika feels toward the player. We should rename this to affection (and adjust the variable names accordingly)
2. I don't like your scale. 0 should be neutral, negative values bad (to -50) and positive values good (to 50). By shifting the scale so 0 is neutral, we allow the possibility of expanding the scale further negative or further positive.
3. Your file monika_mood_system isn't an `rpy`. If you tested this, I don't know how you managed to do that. Since we're gonna rename this to affection, I'm changing this to `script-affection.rpy`
4. Internally, we had some development for a system similar to this. One thing i particularly like about our internal system was variable adding/subtracting of the affection. I see you've done that with various functions, but we would prefer that to be simpler in scale:  
   - 1 function to increase affection, 1 to decrease.
   - both functions affected by modifiers that change depending on your level of affection. This is realistic in the sense that if you have a good relationship with someone, more good things may not increase your affection, but a bad thing would decrease it substantially.
5. Because of the above issues, I'm going to merge this into a new upstream branch. You and @kaido1224  will develop this system on that branch and make pull requests when necessary.

**Comment by ThePotatoGuy** [comment]
The branch is `affection`. Make all changes to that upstream branch.

**Comment by kaido1224** [comment]
Good idea

**Pull request closed without merging**
