### PR TITLE
Sea Rewrite

### PR DESCRIPTION
**Pull request by Olliesama**
Rewrite of the 2 Topics Pull Request.

### CODE REVIEW

**Comment by FireyAmber** [comment]
I'll focus my review on the whole sea part of this topic:

> m  "Life in it thrives and that's pretty amazing you know?"

Could use a comma before you know?

>     m 4h "The ocean floor is in complete darkness, food is scarce. "
    m "And the pressure it can have is overwhelming."

Something that you seem to do quite often is list several things and split them between two lines, this doesn't prove useful and just interrupts the flow while going through it.

>m "Yet despite all the struggles, it's populace persist and adapt."

Reword "it's populace persist and adapt."

>  m 4c "..."

What's the purpose of this line? There's not a reason for Monika to stay silent between these lines.

>     m "Yet even the sea isn't unaffected by pollution"
    m "The coral reefs are dying and many fish species are becoming extinct."
    m "It's really upsetting to think theres so little we as can do..."

How and why does Monika have this much knowledge of the sea?

>     m 1l "Man, the environment just can't catch a break! Ahaha..."

This line doesn't seem like how would Monika take an issue about pollution.

For the rest of the topic, why does Monika know so much about whaling? She doesn't particularly care about animals to know this much about them and ask the player to not buy whale meat.  She is simply vegetarian cause of the carbon footprint that cultivating livestock leaves.
I believe this topic requires some work on the sea section aside from anything that will be mentioned on the beach section of this topic by another dev team member.

**Comment by ashameimaru** [comment]
[ Please note my way of editing is a little different, and I usually make commentary vs making pure corrections as you will see why: ]

Discussing with Amber, I felt that a split is necessary. Here is where I am going to propose the split. I am starting it by just copy/pasting straight through.

```
init 5 python:
     addEvent(Event(eventlabel="monika_sea",category=['random'],prompt="The sea.",random=True))
 
label monika_beach:
    m 3a "[player] have you ever been to the beach?"
    m "I've always wanted to go myself but never found the time."
    m 3j"Imaganing the many sensations it could bring really excites me!"
    m 3a"The fresh sea air, the sound of seagulls."
    m "AS well as the feeling of sand under your feet.."
    m 2b "It would really make a trip worthwhile!"
    m 2j "I bet we would make some lovely memories there."
	return
```

Because I live in a resort city that has a beach, I am making commentary on this portion since well, I am familiar with this stuff! The way I'm proposing this is to make this more of her personal (and your's if any!) experience. So ...

For what reason did she not have enough time to go to the beach? Was it schoolwork? Was it school clubs? etc. [ Keep in mind during Japanese summer break/intercessory, students are often given a big project to do over the summer. School clubs also do major planning during this time too. ]

What kind of "lovely memories" would she like to make? Would she like to make sandcastles with you? Or bury head deep you in sand (or vice versa?) Ride in the ocean waves with innertubes? Eat shaved ice or ice cream with you? Visit the nightclubs (yeah right lol)? Would she play (or be any good at) [suikawari](https://www.youtube.com/watch?v=4_NIQWhx2Ik)? Would you just simply want to lean back on the beach and have a tan? Watch sunrises/sunsets with you? 

Of course, what beaches would she like to visit? Okinawa? Hawaii? Long Beach (California)? Rio de Janeiro? [Miami](https://www.youtube.com/watch?v=IwBS6QGsH_4) Beach? You may make assumptions based on popular media (it happens alot in Japan).

And this is where you could maybe think about what kind of swimsuit she has! Um. You can leave that to your imagination, but don't go too dirt[y](https://www.youtube.com/watch?v=Oai1V7kaFBk)!

It's perfectly fine to throw personal experiences if the things you done would be something Monika would like to do! 

As for the text itself, I am proposing the following to start with. I made some mechanic/grammar corrections but this is more suggested! It is also okay to go for much longer lines!
```
init 5 python:
     addEvent(Event(eventlabel="monika_beach",category=['random'],prompt="Have you ever been to the beach?",random=True))
 
label monika_beach:
    m "You know [player], I've always wanted to go myself but never found the time."
	(add why she never had the time)
    m 3j "I am imagining the many sensations it could bring really excites me!"
    m 3a "The fresh sea air, the sound of seagulls, and the feeling of sand under your feet.."
    m 2b "It would really make a trip worthwhile!"
    m 2j "I bet we would make some lovely memories there."
	(add lots of stuff here.)
    return
```
If you have any questions, please let me know and I can make some suggestions!

**Comment by Olliesama** [comment]
Ok I've rewritten it to be primarily about the beach, I hope it's better.
I've tested it so it doesn't crash but I can't seem to force dialogue in this new version so I don't know how it looks in game. Sorry.

**Comment by kaido1224** [comment]
At first glance, the indentation needs to be fixed here:
```
    m 3b"I've always wanted to go myself but never found the time."
    m 3a"I'would always be busy studying or at my clubs."
    m "It wasn't easy trying to stay on top of everything..."
    m 3m"And whenever I had a break I would usually spend my time at home relaxing."
    m "I rarely had a chance to do so after all."
    m 3h"Sometimes I feel like I might have missed out making some important memories though."
    m 3q"Though I guess the game never had a beach so I couldn't go if I wanted to anyway."
```

A thought I had, what if the player has never been to the beach before, like Monika? Maybe add that as a menu option and then have monika respond by saying something like "Maybe we'll both be able to go to the beach some day and experience it for ourselves together."

**Pull request merged**
