### PR TITLE
Zodiac / Starsign Question

### PR DESCRIPTION
**Pull request by KiddTheManiac**
Added a pool topic  / question on Monika's starsign (Western Zodiac).

I may be able to add a variation for if the player has seen the convo before, but for now I wanted to check if the starsign check would work properly.

### CODE REVIEW

**Comment by KiddTheManiac** [comment]
Just to clarify, it says in the pull request that this is "awaiting changes", but I've actually made a bunch of changes and re-requested a review. Is there anything I need to do right now aside from just wait?

**Comment by Booplicate** [comment]
Will rereview when I can.

**Comment by Booplicate** [comment]
@KiddTheManiac I did some cleanup, fixed a few issues and adjust expressions. You can take a look if you want.

Also, you'll need to change the branch from `master` to `content`.

**Comment by KiddTheManiac** [comment]
Rebased, and changed "And so you are, Nickname!" to "And so are you, Nickname!".

Seems all good to go to me. :)

**Review by jmwall24 — APPROVED** [review]

**Review by Booplicate — APPROVED** [review]

**Pull request merged**
