### PR TITLE
Changes in "monika_closeness"

### PR DESCRIPTION
**Pull request by GitGodScrub**
Changes in the topic "monika_closeness"

### CODE REVIEW

**Comment by multimokia** [comment]
FYI we handle these in #6008. Best to comment it there.

**Comment by GitGodScrub** [comment]
Whoops, alright

**Comment by GitGodScrub** [comment]
Does that include rewritten sentences?

**Comment by multimokia** [comment]
Current awkward phrasing and such all go there. Yes

**Comment by GitGodScrub** [comment]
> FYI we handle these in #6008. Best to comment it there so all typos are handled in one centralized place and PR (#6024)

Just mentioning the # 's in a comment on a pull request, would do the trick, right?

**Comment by multimokia** [comment]
Best to report the issue for historical changes. That, and I'll end up pushing it to #6024 so everything's together.

**Comment by multimokia** [comment]
Closing as I've pushed to typos

**Pull request closed without merging**
