### PR TITLE
Musical instrument easter egg

### PR DESCRIPTION
**Pull request by jmwall24**
Just a small easter egg addition to the musical instrument topic, where if you tell her you play the harmonica, but instead spell it harmonika, she notices and comments on it.  The only part I wasn't sure about was the elif part to add a second option other than piano, I think I got it right, but if not let me know.

### CODE REVIEW

**Comment by jmwall24** [comment]
Made 2 small tweaks in the second commit

**Comment by ThePotatoGuy** [comment]
Should be based to `content` since main focus is adding something.

**Comment by jmwall24** [comment]
Oops, sorry.  How to I change the branch or should I just open a new pull request instead?

**Comment by jmwall24** [comment]
Not sure how to move it, so just created a new PR.  Closing this one in favor of #1697

**Pull request closed without merging**
