### PR TITLE
Potentially illogical dialogue fixes

### PR DESCRIPTION
**Pull request by Wingdinggaster656**
`monika_lastpoem` is available for everyone, and that doesn't make sense to people who have never seen the poem.

A little check was made here to make sure that anyone reading this topic must have read the last poem.

### CODE REVIEW

**Comment by Booplicate** [comment]
I'm not sure if this requires act 3.
Also it will need an update script.

**Comment by Wingdinggaster656** [comment]
> I'm not sure if this requires act 3.

Yeah, I don't think it necessarily requires the player to reach ACT 3, too.
Here the current `conditional` is more like giving a prototype. It would be better if we had a more accurate way to judge.

**Comment by Wingdinggaster656** [comment]
>Also it will need an update script.

Changed in 712b8e4

**Comment by Booplicate** [comment]
Not really, 0.12.9 is the current version, your branch is out of date. You'll also need a sanity check so people who saw it, keep it as is.

**Comment by Wingdinggaster656** [comment]
> Not really, 0.12.9 is the current version, your branch is out of date. You'll also need a sanity check so people who saw it, keep it as is.

Changed in f4c785a, _I guess_.

**Review by Booplicate — APPROVED** [review]

**Review by ThePotatoGuy — APPROVED** [review]

**Review by ThePotatoGuy — DISMISSED** [review]

**Review by Booplicate — APPROVED** [review]

**Review by jmwall24 — APPROVED** [review]

**Pull request merged**
