### PR TITLE
self-pleasure - wrong word used

### PR DESCRIPTION
**Pull request by MarkusRamikin**
"Objectively" sounds weird, since normally it means "without bias" or "relying on objective measures rather than direct perception". 

Doubtless whoever wrote this meant "in an objectifying way", and that would have worked as a rewrite. But "objectification" is such a buzzword nowadays that I felt actually unpacking that concept made for better dialog for Monika.

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
Hmm, actually I think more of that line should be rewritten. Maybe something like this:

`From what I hear, people addicted to self-pleasure often see others as objects, not as persons.`

(We'll let a writer weigh in on this though).

**Comment by MarkusRamikin** [comment]
Oh, the whole dialog is problematic. And someone already has made a good proposal for rewriting it:

https://github.com/Backdash/MonikaModDev/issues/1109#issuecomment-367467245

But it seems to have been ninja-rejected.

**Comment by ThePotatoGuy** [comment]
@monikLover , could you at least mentioning reasoning behind closing pull request #1111 ?

**Comment by MarkusRamikin** [comment]
> @monikLover , could you at least mentioning reasoning behind closing pull request #1111 ?

Or the related issue 1109?

**Comment by monikLover** [comment]
I'll ask a consensus from our writers. Could do with a look-over and a rewrite of the topic.

**Pull request closed without merging**
