### PR TITLE
[New Spritepack] Heart Cut Bikinis

### PR DESCRIPTION
**Pull request by kkrosie123**
- [x] thumbs
- [x] testing

### CODE REVIEW

**Comment by kkrosie123** [comment]
all tested, looks good and works fine

**Comment by multimokia** [comment]
Rebase to content

**Comment by multimokia** [comment]
Rebase to content

**Review by ThePotatoGuy — APPROVED** [review]

**Review by ThePotatoGuy — CHANGES_REQUESTED** [review]
hold up forgot something

**Review by ThePotatoGuy — DISMISSED** [review]
added exprops + merged content to fix folder names

**Review by ThePotatoGuy — APPROVED** [review]
removed wet prop

**Review by jmwall24 — APPROVED** [review]

**Pull request merged**
