### PR TITLE
Take Two of the Masturbation Topic Revision 

### PR DESCRIPTION
**Pull request by juliathegolden**
So it turns out that the original rejection of this may have been an accident.

By popular demand, here it is: new, improved, and on the right branch.

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
should be on `content`, as per the new rules is that anything that requires dialogue review should be in `content`

**Comment by Rai99** [comment]
**Take Three**
Third time's the charm

**Comment by juliathegolden** [comment]
`**_second take_**`

@ThePotatoGuy show some mercy to ya girl it's almost my birthday. 

Should be fixed.

**Comment by monikLover** [comment]
Apporved. Need @aldoram5 to fix current conflicts :tohrusmile:

**Pull request merged**
