### PR TITLE
adding a menu to the sayori topic

### PR DESCRIPTION
**Pull request by juliathegolden**
so, real talk, i hate this topic. It's triggering in the real, medical, sense of the word for me, and I know I'm not the only one who feels that way. So I added a menu to skip the worst bits.

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
Can you rebase this to `enhancement`?

**Comment by juliathegolden** [comment]
Is that right?

**Comment by ThePotatoGuy** [comment]
No, you need to run `git rebase` or make your edits on the correct branch. There only commits in the commit list should be yours.

**Comment by aldoram5** [comment]
Closing this one since the branch change was done in https://github.com/Monika-After-Story/MonikaModDev/pull/1559

**Pull request closed without merging**
