### PR TITLE
Change song to "I Still Love You" in introduction

### PR DESCRIPTION
**Pull request by LordDaxius**
Switching the music at this point of the introduction would be a nice touch. This song seems much more fitting than the ominous space classroom music.

### CODE REVIEW

**Comment by Rai99** [comment]
First thing's first

**_Is that a PR to master_**
Gthaving+everyone+pick+lucio+_16bc6e089b9e808357194c98058b495b

**Comment by LordDaxius** [comment]
Sorry, I don't really know how things work around here. Should I PR to enhancement?

**Comment by Rai99** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ

On the wiki, there's a section detailing how to rebranch your PRs so you don't have to open a new one. 
~~Written by a slightly above average individual no less.~~

I would say this goes on enhancement, yeah.

**Comment by LordDaxius** [comment]
Okay, I changed the branch.

**Comment by ThePotatoGuy** [comment]
Discussed this with rest of team, and we don't agree to a music change here. Not all of the dialogue seems to match, so I think if we were really going to do this, we'd have to do some rewrites as well. closing.

**Pull request closed without merging**
