### PR TITLE
Monika tries to change music - Update script-topics.rpy 

### PR DESCRIPTION
**Pull request by salvo18**
(line 801/831) I've added a random topic with monika that tries to change music, failing.
I've added a sound effect to make mas read it put it in the game folder
[gearupdate.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2609164/gearupdate.zip)

### CODE REVIEW

**Comment by jmwall24** [comment]
First thing, that file you included is not an `.ogg` file, it's an `.mp3` that you just changed the extension on to `.ogg`.  You have to actually convert the `.mp3` to `.ogg` format.

**Comment by salvo18** [comment]
@jmwall24  got that file from a site, weeks ago... i don't know what they've done with it xD

**Comment by ThePotatoGuy** [comment]
With the music menu, the original premise of this topic is out of place. Monika changing the music should just be completely redone, perhaps with her selecting music based on affection/mood/whatever rather than a little joke where she cant change it (especially since she should be able to change it on her own now)

**Comment by salvo18** [comment]
@ThePotatoGuy yeah, this dialogue that I created was just to make the player laugh a little when seeing that monika could not change the music on its own. Maybe as soon as I have time I'll try to add more things based on affection and maybe make her actually change the music :)

**Comment by multimokia** [comment]
Closing as this doesn't really fit given Monika can control the music + tells you how to add custom music.

**Pull request closed without merging**
