### PR TITLE
[New Spritepacks] Chokers

### PR DESCRIPTION
**Pull request by kkrosie123**
- [x] chain
- [x] daisy
- [x] emerald 
- [x] glitter bead
- [x] ribbon
- [x] ruffles
- [x] silk ring
- [x] spiked star
- [x] spiral
- [x] thread ribbon

### CODE REVIEW

**Comment by kkrosie123** [comment]
todo:
- thumbs

**Comment by kkrosie123** [comment]
all are finished code-wise, just need thumbs

**Review by ThePotatoGuy — CHANGES_REQUESTED** [review]
so these have been separated into individual packs, but that's a lot of copying overhead. Making these a single chokers pack with all chokers included would be easier for install (gifting would still be individual). Are you okay with that or do you still want them to be separate?

**Comment by kkrosie123** [comment]
That's fine by me! I do plan on making more chokers in the future though - so maybe multiple packs?

**Comment by ThePotatoGuy** [comment]
ok i will combine into a pack and number it

**Review by ThePotatoGuy — APPROVED** [review]

**Comment by jmwall24** [comment]
assigning @Legendkiller21 for thumbs

**Review by ThePotatoGuy — DISMISSED** [review]

**Review by ThePotatoGuy — APPROVED** [review]
i made the ribbon chokers priority 10 so it can go over OR under the necklace. The spiked star one is now at priority 15 so it goes over the necklace.

**Review by jmwall24 — APPROVED** [review]

**Pull request merged**
