### PR TITLE
"Birthday" Mood

### PR DESCRIPTION
**Pull request by ThePotatoGuy**
#1326 #1171 #1160 #1108 #1050 #924 #614 #430 

**This does not solve the linked issues directly**

This is more like an additional mood where Monika can tell you happy birthday when you click a certain button. Monika will remember the date, and we can leverage that in a future update. 

NOTE: A calendar ui is still more appropriate, but this can tide people over until that gets completed.

### Technical:
* `_mas_player_bday` is the `persistent` that contains a `datetime.date` of the player's birthday.
* a new section in script_ch30 has been added for special triggers that should occur on session start.

### Additional:
* This mood can only be triggered once a day. It hides itself when it has been seen.

### CODE REVIEW

**Comment by MonotoneHeart** [comment]
So if I accidentally said that today was my birthday, how would I go about fixing the date?

**Comment by kaido1224** [comment]
wait til it's your actual birthday and tell her then?

**Comment by hkight** [comment]
Mine was yesterday, and this update was released today... I wish there was a way for her to remember that so she doesn't get it wrong next year.

**Comment by Nr-9** [comment]
soooo I wanted to try it out and I clicked it and said that my birthday is today (it isnt) and so after that I go back and I wanted to change it to my actual birthday but the button was gone QwQ
How do I change it now? ~Thanks in advance OwO

**Pull request merged**
